### ISSUE TITLE
request beautifier code

### ISSUE THREAD

**Issue by septs** [NyaaCat/RPGitems-reloaded#10]
https://github.com/NyaaCat/RPGitems-reloaded/blob/master/src/main/java/think/rpgitems/Events.java
this code indentation.......

**Comment by Taiterio** [comment]
Running the eclipse built in formatter on all files, tweaked to leave line wrapping for comments and code alone because it can cause ugly bits of code. Check the next commit on it and please give feedback on how the style should be changed even further :)

**Comment by RecursiveG** [comment]
Reformatted with IntellijIDEA, see 65d884e
@Taiterio Please use 4 spaces instead of a Tab

**Comment by Taiterio** [comment]
May have reverted some of your changes to the files I modified in commit a1824a8edb01b941247ef65527eb28e451dec3a9 with my merge in commit 943d18781b9760c08a136811df566ef68c5b7465. I'm very sorry about that >.<'

Reconfigured eclipse to now replace any tab into 4 spaces :)

**Comment by RecursiveG** [comment]
@Taiterio Well that's fine. I just formatted the code and do no modifications to the logic.
There are indeed some differences between Eclipse&IDEA's format but that's not a big deal.
