### ISSUE TITLE
[BUG] RPG no longer passes Righ-Clicks to trigger mcMMO Abilities (due to #89's fix?)

### ISSUE THREAD

**Issue by Formula350** [NyaaCat/RPGitems-reloaded#100]
- This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
- RPGItems 3.5.108

The fix that took care of #89 has now seemed to be causing RPG weapons not passing right-clicks to mcMMO *at all*. For example, while using a sword it used to activate mcMMO's Serrated Strike ability, now nothing occurs except the RPG power (if it has one). 
 
I don't know if this is something that's addressable or not, though?

**Comment by RecursiveG** [comment]
The right-click works fine for me.
v3.5.111
git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
mcMMO v1.5.04-SNAPSHOT

However, when left-click, there must be a actual damage to active Serrated Strike. If the damage of the rpgitem is set to 0, the ability will not be activated.

Please try with a new item without any power on it and also check the console log.

**Comment by Formula350** [comment]
Huh... maybe things were just acting glitchy that day... It does indeed work it seems.

My apologies!!
