### ISSUE TITLE
Inconsistent Language File

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/RPGitems-reloaded#101]
The main language file `en_GB.lang` was changed but the other language files weren't.
This may cause problems (see #91 #98 cf9447c5a89339b9b5b48de6d1a8c37368ae6e30)

We need a way to keep the language files updated among Github Transfix and CI
@phoenixlzx @Arthur2e5

**Comment by Arthur2e5** [comment]
Transifex provides some sort of sync ability. However, due to format limitations reported at #49, this is gonna cause a lot of pointless commits that involves adding and removing the backslashes over and over...

**Comment by Librazy** [comment]
We have NyaaUtilsLangChecker now
