### ISSUE TITLE
Make rpgitems enchantable

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/RPGitems-reloaded#102]
It seems RPGItems can handle enchantments correctly. But they can not be enchanted in enchant tables. Should we make this possible? @phoenixlzx

**Comment by Formula350** [comment]
If I may weigh in... If it is added/changed to allow players to use tables to enchant them, could it be assign to a permission? Say perhaps `rpgitems.can.enchant`, which would allow them to use the table to enchant or an anvil to apply a book. Then later if renaming via Anvil is decided to be added, it could be given an intuitive permission like `rpgitems.can.rename`.

After just stumbling across their ability to be enchanted, but only via /enchant command (or similarly, I'm sure), I have been thinking of all the new things my staff and I will be able to offer players. However, it's that key element, that only my staff can create the items, which keeps the balance of the items in check. Players being able to add their own enchants would cause quite a stir for us.

Thanks :D

**Comment by RecursiveG** [comment]
@Formula350 Yes, a permission node will be assigned.

**Comment by phoenixlzx** [comment]
Will this work with Essentials `/enchant` command?

**Comment by Formula350** [comment]
Yes, it works fine with Essential's `/enchant`. That is how I've been doing it so far. 
*However*, the vanilla `/minecraft:enchant` does **not** appear to work, and I suspect it is due to RPG blocking enchanting through the Enchantment Table.

**Comment by Librazy** [comment]
You can clone enchant from other item now

**Comment by Formula350** [comment]
I tried to using the Clone function a couple days ago after discovering it, but must say... I was unable to get it to work, at least with version 3.5.262.
Mainly this was due to lack of adequate command Help output, so I was sort of just typing in stuff and hoping it would work. :P 

Any tips? Or is build .275 featuring improvements to this that were broken in .262?

**Comment by DiggerGamingYT** [comment]
Im looking to implement players enchanting their rpg items and I cannot find what permission is needed to be able to enchant these items in an enchantment table. What permission or command do I need to enter to give the permission
