### ISSUE TITLE
[BUG] Latest RPGItems makes players unable to consume while constantly hit

### ISSUE THREAD

**Issue by Laos1996** [NyaaCat/RPGitems-reloaded#104]
As title says, in latest version of RPG items, I guess its due to fix for McMMO, if you try to consume something, like hold right click for god apple, and someone hits you with fist 24/7 it will reset your eat for it and you wont be able to consume at all.

Before you tell me it could be other plugin, I've checked 3 times, its RPGItems doing it, not NoCheatPlus, nor any other plugin.

**Comment by RecursiveG** [comment]
Is it a normal Gold Apple or RPGitem apple?

**Comment by Laos1996** [comment]
I've tried with Normal Golden Apple and Normal God (Notch) Apple.

**Comment by RecursiveG** [comment]
I cannot reproduce this issue with version v3.5.111
git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
I stand in a pit filled with zombies. With a 99% armor chestplate on. When been hit, the consuming process seems to be reset. But if hold right button pressed, it will eventually be consumed.

**Comment by Laos1996** [comment]
I meant hit by player, sorry for confusion. Furthermore, you should be able to consume items no matter of the occasion you are in.

**Comment by Laos1996** [comment]
Regarding the issue, here is an example, trying to consume an god (notch) apple while RPGItems is loaded vs RPGItems disabled (latest version on spigot).
https://www.youtube.com/watch?v=GjmxsJt3-Q8

Version I use
https://gyazo.com/6712417fb5105ddccf03a7c2243d5e5f

**Comment by Laos1996** [comment]
So, is this issue even going to get taken into consideration? It was not even properly tested from your side.

**Comment by Taiterio** [comment]
Cannot reproduce on git-Spigot-a1b8bf3-f01861f (MC: 1.9.2) nor on PaperSpigot git-Paper-716 (MC: 1.9.2) with only the RPGItems plugin installed. I'll try to run some tests with your reported version.
