### ISSUE TITLE
[REQUEST] Tools as Weapons: disabling their Tool-abilities completely.

### ISSUE THREAD

**Issue by Formula350** [NyaaCat/RPGitems-reloaded#105]
On my server we have long made weapons that utilized various non-weapon items in MC, as I suspect most servers who also use this plugin have no doubt done. For example making the Pickaxe a "Crossbow" since the texture is quite a perfect analog, or Hoes as Scythes and Shovels (Spades) as Clubs with a little imagination. Overall this works just fine thanks to RPG's ability to custom set a damage.

However, there's a small problem that arises if you have the weapons configured with a Durability of Infinite (-1), as now players are able to use their "Crossbow" as an infinite Pickaxe. Now with the "Crossbow" it was an easy workaround, just change it to have a Durability and no problem, as the Arrow power is what is getting used. Yet, on the Hoes and Shovels, you are making them be a direct-contact weapon and therein lies the issue. If you give them Infinite Durability you solve the breaking problem, but create the Infinite Tool problem. Axes have the same problem, and our **only** saving grace on this has been thanks to mcMMO's "Treefeller" special axe ability, which will at random destroy the axe; RPGItem or not. Now we didn't tell our players it's exclusive to using the ability, we just said "if you use it as a Tool and it breaks, that's your own fault" (some of our prized weapons are limited-run quest items, so it's impossible to get them back).

While disabling their tool ability would be ideal I think, I can only imagine it might not be so simple, so I do have an alternative that may be easier to accomplish... If the "disable tool" isn't possible, then perhaps being able to provide a per-item toggle where if said item is set with a Durability, it only applies to contact with non-living entities. In other words, when mining with an Infinite Durability Shovel that is set as a weapon, it will lose durability like a normal shovel would; however, when hitting a player or a zombie with that same shovel it will **_not**_  lose durability.

Possible command to toggle this may be something like...
`/rpgitem <itemname> toggle tool` or `/rpgitem <itemname> isTool

**Comment by RecursiveG** [comment]
It's not easy to make them lose duration when used as tools because the duration will automatically recover when used as a weapon.
One solution may be adding a new power called `PowerNoDig` to prevent player from harvesting blocks.

**Comment by Formula350** [comment]
As a possible alternative could RPGItems actually Listen for a Dig Event and simply Cancel it out, or I would that use way too many processor time and hurt TPS?

If not, I honestly think that having the ability to completely *prevent* items from even being able to dig or break blocks would be just as good. I just thought that having it cancel out a durability (duration) event when it is acting as a weapon would be easier. 

As a means for how to tag the specific items so RPG is able to determine how to deal with durability, perhaps some sort of hidden NBT value can be set? Or now that I think about it... RPGItems seem to have a lot of excess Color Code added on to the items before the names. For example, here is a what the NBT.Name data on a sword called "**Ice VII**" reads: `§0§0§0§0§0§0§7§e§7§l'§lIce VII'`. When I did `/rpgitem ice7 display`, I put in `&7&lIce VII`, and it was RPGItems that added the `§0§0§0§0§0§0§7§e`. 

ANYWAYS, my point is that you could use that as a coding structure:
If an item is a weapon-only, it would be for example: `§1§0§0§0§0§0§7§e`
If an item is a tool-only, it could be set as: `§2§0§0§0§0§0§7§e`
Only the first few color codes would change and be looked at to determine how an item is handled.

*(I apologize if the last two paragraphs are confusing. If they are, just ignore that part)*

**Comment by Taiterio** [comment]
This should all be possible using the preset item NBTTags. Weapon-only items get their canBreak tag set to nothing, Tool-only ones get their attack damage set to 0. Once I get around to it, I'll add the support for NBTTags so we can also use things like Attack speed :)

What won't work is setting hidden custom NBTTags, as they are lost whenever a plugin changes the item in any form.

**Comment by Formula350** [comment]
@Taiterio That would be awesome! I never considered NBTs, and I feel like quite a derp for not heh

*-cough-* You should also add your CustomEnchatments support via a `Power`, like `Power CustomEnchantments <enchant> [level]`, having it poll the CE config file directly when outputting what <enchant> options are available (that way it'd reflect personalized changes made by anyone). ;) ;)

**Comment by Taiterio** [comment]
@Formula350 That sounds like a great idea :)

On the part of the config polling, should it then just show the list of all enabled CustomEnchantments and their corresponding max level?
