### ISSUE TITLE
[BUG] Builds 110-116 break Lore text; missing line-breaks.

### ISSUE THREAD

**Issue by Formula350** [NyaaCat/RPGitems-reloaded#106]
- Spigot 1.8.8 
- RPGItems builds: 110, 111, 112, 114, 116 
 
I noticed this last night while on build 114: ...
![lore-110-116](https://cloud.githubusercontent.com/assets/10291023/14445821/330137ac-001e-11e6-975f-1b1ada460958.png)
So when it wasn't restored after a restart, I started testing out the rest of the builds one by one, which eventually it turned out to be build 109 where it was working again. Perhaps something to do with the [`Bad power description workaround`](https://github.com/NyaaCat/RPGitems-reloaded/commit/cf9447c5a89339b9b5b48de6d1a8c37368ae6e30)?

**Comment by RecursiveG** [comment]
It's from [this commit](https://github.com/NyaaCat/RPGitems-reloaded/commit/3849e2a530c0fe46302e6ad932932ec6830128a2#diff-e34734896905a4da10936c0f210a851cR470).
I think the function of `lore` can be completely replaced by `description` and thus reduce code complexity.
If there are some particular reasons to use `lore` rather than `description`, please let me know and I may revert that change.

**Comment by Formula350** [comment]
Primarily it is the fact that a long established aspect of RPGItems is being greatly changed, which anyone familiar with the plugin will automatically expect the lore to wrap by default. Similarly, `lore` is automatically formatted for us, with pre-applied quotes.

The fact that `/rpgitem <itemname> description add <text>` is quite a bit longer than `/rpgitem <itemname> lore <text>`, which makes it easier while making items. Generally, the items we create do not require a long enough lore to need to utilize a command block for. So while the 2-3 words that "description add" eats up is not too much, it still introduces more work when creating an item on the whole (plus: &e"). On top of that, just to change a line will further eat up due to the change of command for `set #`.

Lastly, there's the fact that using `description` actually is not a substitute at all due to it not wrapping text either. Which basically loops right back to my point above.

The **only** Pro to this is that you can enter in tons of lines of "lore" simply through the in-game command. However, in my opinion that's still requires a lot more effort, as by that point I'd rather just use a command block to ender in the long `lore` text.... which is now not possible since it crowds the item right off a player's screen, making any details/description rendered irrelevant *(I had to change my GUI size to the smallest option just to capture that screenshot)*

While I am not a coder, I can fully appreciate the desire to cut down on code, or code complexity for that matter. Also I **very** much appreciate addressing the matter about being able to separately toggle the `ArmorLore` and `PowerLore` lines, as I had already accepted the it would be  "All or nothing". I just feel like my request, while leading to a "fix" for a few other bugs (originally), will now have resulted in changes which ultimately upset the vast majority of users of the plugin. 

As in my case, well I don't know *exactly* how many items we have as we have of course deleted some which didn't turn out; however, most are kept and our current items.yml sits at 553Kb, with over 23,000 lines, and a `pos: 889`. In short, the changes to Lore would require hand-editing roughly 800 items in order to convert the lore to descriptions, **and** then to make sure they all look good. That'd take me about a week to accomplish, at best. :\

Don't get me wrong, my staff and I think you all are doing an amazing job and feel you are really kicking ass at making RPGItems better. So for that, and on their behalf, ***Thank You!*** :)

**Comment by RecursiveG** [comment]
I've added the line-breaks back. Try the latest build.
But it may behave slightly different from the original one since I have to take `toggleArmorLores` and `togglePowerLores` into consideration.
Also, I haven't tested it rigorously so it may has a little chance to break (e.g. not loading some items) on some edge cases.
Feel free to close this issue if you are satisfied with it.

**Comment by Formula350** [comment]
Much appreciated :D 

I didn't see any startup errors, and the plugin does appear to be functioning normally. The `Lore` is displaying correctly, and continues wrap correctly after `toggleArmorLore` and `togglePowerLore` on the item.
![astraea-118](https://cloud.githubusercontent.com/assets/10291023/14505305/8ce01400-0186-11e6-89a8-e444cf2866df.jpg)
The **only** "bug* (not that it is one), is that in addition to a space before it all, there is also tons of extra color code in the `Lore`. While this is purely cosmetic at first blush; however, this will cause problems for any other plugin that requires consistent formatting. For example, Quests had dropped RPGItem support quite awhile ago due to the RPG being abandoned, and so for certain Quest where we have them deliver RPGItems, that space and colorcode actually breaks the quest :( So in actuality the majority of our quests will need fixing *again*. Here's an example of how Delivery stages are stored since RPG support was dropped (It takes whatever item is in your hand):
Quest looks for this:
![quest](https://cloud.githubusercontent.com/assets/10291023/14508234/7a1dfd88-0194-11e6-8f3e-7c1e3378d198.png)
RPG Build 118 recipe crafts this (changes are highlighted):
![quest-118](https://cloud.githubusercontent.com/assets/10291023/14508499/b19f0080-0195-11e6-926e-9350b2ff0ae8.png)

Since I suspect this sort of change will happen often, I'm going to make a request with the Quests dev if he can re-add RPGItems support. That Dev isn't anywhere near as productive as you all, so I don't know how likely (or soon) it'd be added back in :-S

Other than that, I have only tried it out on my Test server, but so far everything seems OK. I'll be moving it over to my main server now and will report back any problems

**Comment by RecursiveG** [comment]
Got it. I will try to fix that.
But you may not need to re-setup the quests at all. As long as the first line of the lore is correct, rpgitem will automatically refresh all lore every time when used. So those items given with the old lores are still valid and usable I believe.

**Comment by Formula350** [comment]
It's ALMOST back to how it was! I wish that Quests hadn't dropped support or this wouldn't be a problem... I feel **so** petty making a fuss over it, so I apologize for that :(
Build 119 - Still has the `space` before `&e` in `Lore`, missing `&o` on each line:
![sotn-119](https://cloud.githubusercontent.com/assets/10291023/14547327/72e82502-027a-11e6-8b5e-07dda56bb147.png) 

Build 108:
![sotn-108](https://cloud.githubusercontent.com/assets/10291023/14547358/bd08add2-027a-11e6-96ed-2b5def71f561.png)

**Comment by Formula350** [comment]
haha OMG. So it turns out that in Build 108, the space ***was*** there the whole time, but it was simply being added and the *end* of the first line of Lore. In other words, a bug, but one that would never have been exposed had it not been for all of this.

Anyways, I think I have been anal enough on this issue and you have gone way further than needed to address this. I'm definitely not going to ask you to re-introduce that "bug", so I'm calling this all fixed and I'll manually enter in the space to the quest file lol

HUGE thank you for tolerating me!! :)
