### ISSUE TITLE
Rpgitems not work when on left hand

### ISSUE THREAD

**Issue by mzkws2008** [NyaaCat/RPGitems-reloaded#107]
rt，rpgitem在左手上左右键使用都不行
服务器是最新版PaperSpigot

**Comment by RecursiveG** [comment]
1.9 compatibility problem. #83 
@Taiterio Any ideas?

**Comment by Taiterio** [comment]
Offhand items are not detected by the plugin as of yet, getItemInHand and getItemInMainHand only resolve to the main hand the player chose. Going to add some checks for offhand RPGItems, although I believe that the rightclick event is the only one necessary.
