### ISSUE TITLE
New power: torch

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#11]
A power that shoots one or several (configurable) torch (or something different), and stick torches on walls and ground nearby. After sometime the torch automatically removes itself.

Something like illumination flares.

**Comment by Taiterio** [comment]
Added in commit 49c74edf31a71bae848e44eb0d74f32a6ea0e836. I have marked some problems in the code. Players are able to create an infinite amount of torches from this power, however I am not able to cancel the physics event that causes this. I have tried getting this to work, but even though the code for cancelling the physics event is triggered, the torch still breaks and drops an item.
