### ISSUE TITLE
RPGitems not working on bukkit 1.9.1

### ISSUE THREAD

**Issue by thanasishadow** [NyaaCat/RPGitems-reloaded#112]
I have a bukkit server and i am using [this](https://github.com/NyaaCat/RPGitems-reloaded/releases/download/1.7.2-v3.5.106/RPGitems-reloaded.jar) version of the plugin. At first it seems to work fine but any other command except "/rpgitems" doesn't work, it doesn't say anything.
Also it spams the console with error messages.
[1461511999072-log.txt](https://github.com/NyaaCat/RPGitems-reloaded/files/234601/1461511999072-log.txt)
Here is the config
language: en_GB
autoupdate: false
defaults:
  hand: One handed
  sword: Sword
  damage: Damage
  armour: Armour
support:
  worldguard: false
version: '0.5'

**Comment by cyilin** [comment]
RPGItems is only compatible with spigot

1.7.2-v3.5.106 is for spigot 1.7 (#92)

**Comment by Formula350** [comment]
(Ugh I meant to post this like 2 days ago...)
That `1.7.2-v3.5.106` you see, means it's for Minecraft 1.7, which is very different from 1.9.

I don't know if the current builds have 1.9 support added, but the last one specifically for 1.9 is this build of 105: https://github.com/NyaaCat/RPGitems-reloaded/tree/1.9-v3.5.105
