### ISSUE TITLE
Unbreakable items with defined damage value. Allows damage-value-based texture customization

### ISSUE THREAD

**Issue by yyeerai** [NyaaCat/RPGitems-reloaded#113]
详细情况可以看这个链接
https://www.spigotmc.org/wiki/custom-item-models-in-1-9-and-up/

希望支持skillAPI

感谢你们继续更新这个不错的插件

**Comment by cyilin** [comment]
use command:
/rpgitem [item] item [ItemID] [DataVaule]
/rpgitem [item] power unbreakable

例如: /rpgitem [item] item wood_hoe 1

**Comment by yyeerai** [comment]
这样并不行

**Comment by RecursiveG** [comment]
这个需要客户端的材质包支持吧？

**Comment by Librazy** [comment]
目前已经有有自定义模型支持

**Comment by prozhong** [comment]
since this kind of item has custom durability and is setUnbreakable(true)
would it affected by enchantment MENDING ?
If so, the custom model would change.

既然物品有固定的耐久度并且不可损坏
还会被经验修补影响 来变动耐久度吗？
有人验证过吗
