### ISSUE TITLE
RPG Item ''Power timer''

### ISSUE THREAD

**Issue by OkappaAN** [NyaaCat/RPGitems-reloaded#114]
Hi guys! I have a suggestion for you: Can you add to the /rpgitem power command another option called ''timer''? Like, I right click an item with a certain command, if the timer is set to 10 ticks, the command will be activated after 1 second. Thanks for reading, I'll really be happy if you could do this!

**Comment by RecursiveG** [comment]
Generally, powers on one item work independently and they cannot affect each other.
We will consider this but it may take some time.

**Comment by Formula350** [comment]
@OkappaAN Are you requesting a Delay? So that `# of Ticks` after `Right Click` it executes the `Command Power`?

**Comment by OkappaAN** [comment]
Exactly

**Comment by OkappaAN** [comment]
Formula350 that's exactly what I wanted :D

**Comment by OkappaAN** [comment]
Is there already that feature or are you going to add it soon? I really need it

**Comment by OkappaAN** [comment]
Could someone answer please? I would really like to have that feature

**Comment by RecursiveG** [comment]
@OkappaAN 
Is that acceptable to add this feature to `PowerCommand` only?
(By adding a new power called `PowerDelayedCommand`)
I can add this tonight but I do not have that much time to apply this feature to every Power.

**Comment by RecursiveG** [comment]
Please use the latest build and execute `/rpgitem {itemName} power delayedcommand` to see usage.

**Comment by OkappaAN** [comment]
Thanks a lot
