### ISSUE TITLE
Critical: People can enchant amors rpg

### ISSUE THREAD

**Issue by xxBoWiExx** [NyaaCat/RPGitems-reloaded#115]
Hi, with the old plugin RPG-Items you cant enchant armor or weapons rpg, but with this one you can, and that is very OP because with an armor rpg and enchanted is very dificult to kill players. Regards

**Comment by RecursiveG** [comment]
I cannot reproduce this issue.
Please provide:
- Your server version, use `/version` command
- Your plugin version
- Take the item which has his problem in hand and issue `/rpgitemupdate inspect` command
- Give yourself a new rpgitem and test if the issue still exists.

**Comment by xxBoWiExx** [comment]
-  Server Version 1.8.8 R0.1
- Plugin version: 3.5.102

If I givemyself a new rpgitem, that item would be ok, but the problem is that users can enchant the rpgitem, with the old rpgitems (thinkofdeath) if you try to enchant, the item becomes to a normal item, but with this one, people can enchant all the rpgitems.
