### ISSUE TITLE
A 1.7 version for the new update

### ISSUE THREAD

**Issue by OkappaAN** [NyaaCat/RPGitems-reloaded#118]
Hi guys there isn't a new 1.7 version of the update but just for 1.8 and 1.9 I guess. I tried installing but it doesn't show any command so it is not working. Can someone give me a link for it?

**Comment by RecursiveG** [comment]
New build was pushed to release page.

Note that 1.7.x branch is no longer under active maintenance so we cannot guarantee it will work properly. Remember to backup.
Also, please consider updating your server.
