### ISSUE TITLE
Allow custom defaults for items

### ISSUE THREAD

**Issue by hjklr54679** [NyaaCat/RPGitems-reloaded#121]
I never really understood why, in the _config_ file, you can't configure the defaults for items. It's always stuck at the normal settings and automatically reverts itself back if you try to change it. At the very least, remove it from the config.yml as it's very misleading to the end user.

**Comment by RecursiveG** [comment]
Cannot reproduce.
Change values in `default` section do make a different default item.
The server does not revert the changes either.
