### ISSUE TITLE
Crafting items does not work with items with damage values

### ISSUE THREAD

**Issue by alien4rmspace** [NyaaCat/RPGitems-reloaded#122]
For example if I wanted my players to be able to craft an item that drops from a boss I would make the boss drop an item like blaze_rod:1001 and blaze_powder:1001 and I'll set the recipe with the exact items, but when they try to craft the item nothing appears.
Or could it be possible to make it so you can use item name and/or lore to craft an item. 
An example is if I made an item's crafting recipe with 3 renamed blaze rods and an added lore players would not be able to craft the item using regular blaze rods. This is the reason I use damage values in crafting recipes so players wouldn't just use regular items to craft items, but if renamed or added lore items worked it would make everything easier, thanks.

**Comment by RecursiveG** [comment]
The item not appearing problem may be caused by the “chance” feature.
Especially when you are updating from an old version.
See #87 . This discussion may help.
