### ISSUE TITLE
Suggestion: Allow cooldown for consume and food

### ISSUE THREAD

**Issue by hjklr54679** [NyaaCat/RPGitems-reloaded#124]
Not that big of a deal, but when using consumable items I do not want players to accidentally lose their items because the ability on the consumable had a cooldown but not the consumable itself. Food items will frequently "double-click" for me as well and I would like to be able to add a small cooldown.

**Comment by RecursiveG** [comment]
The double-consumption bug has been fixed for 1.9. You do not need to add cooldown time manually.
You can still add PowerConsume with cooldown time using `/rpgitem [itemName] power comsume [cooldownTicks]`
Please use the [latest release](https://github.com/NyaaCat/RPGitems-reloaded/releases)
