### ISSUE TITLE
请求新功能 乾坤一掷

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/RPGitems-reloaded#130]
一个可以把自己的节操丢出去的道具。。。
左键：击中怪物或者玩家固定造成当前持有者5%金钱总额伤害并损失10%金钱总额
右键：投掷箭出去，使用一次损耗1w金钱，伤害待定。。。

**Comment by Talithaald** [comment]
seriously dude -_-

**Comment by ASuperthings** [comment]
你好逗!
Interesting!
