### ISSUE TITLE
Simple Request

### ISSUE THREAD

**Issue by Talithaald** [NyaaCat/RPGitems-reloaded#131]
1. Add /rpgitem Example power potiontick [Amplifier] [Effect] `[Duration]`
2. Add a shorter command `/ri, /ritem, /rpgi,` as /rpgitem
3. Add A Different Item ID For Each RPGItem That Has Been Created, So It'll Available To Sell At
   Chest Shop / SignShop / Essentials iEconomy Plugin
   (ex: RPGItem "Example" Item is made of DIAMOND_SWORD That Has ID 276, so make it 276/1 and so on and if the item is IRON_PICKAXE And It Has ID 257 Make it 257/1/2/3/4/5 and so on)

Regards.
Haliem

**Comment by Librazy** [comment]
1. Have it now.
2. Use tab completion
3. We don't use custom id but lores and nbts. Most shop plugin support that.
