### ISSUE TITLE
Error with RPGITEMS 1.9

### ISSUE THREAD

**Issue by gleng1** [NyaaCat/RPGitems-reloaded#132]
If i wrote /rpgitem gg create, Minecraft in to write anything but the console says this:[16:31:40 INFO]: NecromancerX69 issued server command: /rpgitem gg create
> [16:31:40 WARN]: java.lang.reflect.InvocationTargetException
> [16:31:40 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [16:31:40 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [16:31:40 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [16:31:40 WARN]: at java.lang.reflect.Method.invoke(Method.java:498)
> [16:31:40 WARN]: at think.rpgitems.commands.Commands.exec(Commands.java:186)
> [16:31:40 WARN]: at think.rpgitems.Plugin.onCommand(Plugin.java:129)
> [16:31:40 WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
> [16:31:40 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
> [16:31:40 WARN]: at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:624)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.PlayerConnection.handleCommand(PlayerConnection.java:1298)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:1158)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:37)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.PacketPlayInChat.a(SourceFile:9)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13)
> [16:31:40 WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> [16:31:40 WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:679)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635)
> [16:31:40 WARN]: at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539)
> [16:31:40 WARN]: at java.lang.Thread.run(Thread.java:745)
> [16:31:40 WARN]: Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
> [16:31:40 WARN]: at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:360)
> [16:31:40 WARN]: at think.rpgitems.item.RPGItem.(RPGItem.java:113)
> [16:31:40 WARN]: at think.rpgitems.item.ItemManager.newItem(ItemManager.java:186)
> [16:31:40 WARN]: at think.rpgitems.Handler.createItem(Handler.java:90)
> [16:31:40 WARN]: ... 22 more

**Comment by RecursiveG** [comment]
Same as #125

**Comment by gleng1** [comment]
I using Spigot ...
1.9
