### ISSUE TITLE
Can't Use Power

### ISSUE THREAD

**Issue by Talithaald** [NyaaCat/RPGitems-reloaded#134]
As The Title Says.

I Cannot Hit Players Using RPGItem Power, Such ass Rumble // Fire // Skull / Snowball When Im Aiming At The Player.

I can activate when i aim at the floor :/ Well hope this'll get a fix :bird:

**Comment by alien4rmspace** [comment]
I can confirm, when using rumble without looking at the floor it will cast the effect but will not hit players.

**Comment by Talithaald** [comment]
@alien4rmspace you're getting in wrong.

what i meant was. you aim players, right click, power fireball ( it will not shoot fireballs ) but it triggers cooldown

**Comment by RecursiveG** [comment]
Cannot reproduce. Please make sure that you are using the latest version.
Please provide the complete command list to create that item.
Also, please check if there's any error shown in the console when using the item.
