### ISSUE TITLE
RPG item Recipe gives me Vanilla Item.

### ISSUE THREAD

**Issue by Shinidk** [NyaaCat/RPGitems-reloaded#137]
Well, today i tried to create a rpg item and then add a recipe for it, the item worked fine but when i tried to add a recipe it doesnt work, /rpgitem Energetic recipe 100, and then it open the GUI, but when i try to craft the item it gives me a vanilla item in my case it gives me a mushroom stew... can someone help me with this? recipe its really important to my server! My server its 1.8.8 Spigot.

**Comment by Talithaald** [comment]
@Shinidk  dude, recipe 100 = 0.1 chance, while 1 gives you 100chance, so /rpgitem Energetic recipe 1 for 100% 2for 50%

**Comment by Shinidk** [comment]
Omg talithaald thx so much! I worked :)
