### ISSUE TITLE
Change the way of being unbreakable(durability infinite)

### ISSUE THREAD

**Issue by ASuperthings** [NyaaCat/RPGitems-reloaded#140]
Now,if the rpgitems which are unbreakable are damaged,the plugin will fix the item.
But do you think if the rpgitem are damaged too much to fix(breaked, been disappeared) the plugin could not fix it!
So, You can add a NBT(Unbreakable) to the item to protect them form being breaken).
That's will be better!

**Comment by RecursiveG** [comment]
Please use `/rpgitem {itemName} power unbreakable` instead of `/rpgitem {itemName} power unbreaking` if you want the NBT version of unbreaking ability.
See #88
