### ISSUE TITLE
Power consume with potions

### ISSUE THREAD

**Issue by OkappaAN** [NyaaCat/RPGitems-reloaded#142]
guys, when I try to add the power consume to a potions like strenght, it doesn't work because the player is drinking it. Is there a way to disable the item function and make the power consume work?

**Comment by Bowbuck2** [comment]
I Also Have This Problem

**Comment by RecursiveG** [comment]
Bow, Potion, Snowball and Egg are designed to be like this.
It's the intended behavior and changing this may break backward compatibility.
You may have to use another item instead of potions.
