### ISSUE TITLE
Add Power ArrowRain

### ISSUE THREAD

**Issue by pianwan** [NyaaCat/RPGItems-reloaded#145]
Rightclick to shot ArrowRain.
range,number,damage can config.

**Comment by phoenixlzx** [comment]
I have same idea about it.

When right click, shots arrows from sky to the area player pointing on. Just like Arrow Storm in Assassin's Creed.

Command example: `/rpgitem item power arrowstorm [cooldown ticks] [attack radius] [arrows per tick] [duration] [damage per arrow]`
