### ISSUE TITLE
Updater is using old API

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#15]
The built-in updater is using old curse site API. If we need the auto-update functionality, new update sources should be investigated.

Otherwise I think relative code should be removed from source.

**Comment by Taiterio** [comment]
Was already thinking about that :)

I'll upgrade it to use the newest release found on here within the next few days

**Comment by RecursiveG** [comment]
Maybe we can simply remove the code before stable releases are available?

**Comment by Taiterio** [comment]
That sounds like a pretty good idea considering the enormous amount of builds that are generated currently
