### ISSUE TITLE
Durability-Bar is too long

### ISSUE THREAD

**Issue by ghost** [NyaaCat/RPGitems-reloaded#153]
The durability bar is double the lenght it should be.
I suspect, that the plugin thinks the durability-bar char is half the length it actually is.
![rpg-item](https://cloud.githubusercontent.com/assets/2065024/17533438/f373019a-5e84-11e6-8c32-ebeb2931b675.png)
(I'm sorry for the text, i hope it still helps.)

**Comment by Librazy** [comment]
Numeric bar may help
