### ISSUE TITLE
物品合成不支持Lore

### ISSUE THREAD

**Issue by 0w0xk0w0** [NyaaCat/RPGitems-reloaded#154]
我在bbs回帖，私信你都不理。。我只能来这里了
合成表貌似不支持lore，不支持rpgitems的物品哎
比如物品1要用材质为石头的物品2和3合成，结果用2块原版石头就可以合成了。。。
我不知道这是BUG还是我的问题。。反正求解答。。。
别再不理我啊。。。。。QAQ

**Comment by RecursiveG** [comment]
经过测试未发现问题。
请提供你使用的Minecraft版本和Rpgitem插件版本。
请确保使用的是最新版的插件。

duplicate #144

**Comment by 0w0xk0w0** [comment]
额，Paperspigot1.8.8，在bbs内下载的1.8的版本，就是3.5.133，我用rpgitems3,4,reloaded都是这个问题。。。

**Comment by 0w0xk0w0** [comment]
并且我在各个腐竹群里问他们，他们都说是不支持lore的。。我就来这里反馈了

**Comment by RecursiveG** [comment]
相关功能已backport至1.8版本，请下载最新的版本使用 [1.8-3.5.140](https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.8-v3.5.140)

注意：建议使用 Minecraft 1.10 版本，旧版本的插件不会得到及时更新。
