### ISSUE TITLE
Enchantment Feature

### ISSUE THREAD

**Issue by Atracador** [NyaaCat/RPGitems-reloaded#155]
Hi! I've been trying to create a simple item that drops from a mob and has an enchantment, but there is no way to make an RPG item that is enchanted. Could it be implemented? I suggest making a command such as:
/rpgitem [Item] enchant [enchantment] [String]
Thank you for reading! Have a nice day! Awesome plugin btw.

**Comment by Librazy** [comment]
You can clone enchantment to RPGItem now
