### ISSUE TITLE
Remove vanilla weapon/armor text? or use similar system

### ISSUE THREAD

**Issue by iamawesomebro** [NyaaCat/RPGitems-reloaded#157]
My helm says 5% but it still has the vanilla text below for a diamond helm +3 armor, etc, is there anyway to remove the vanilla text. How closely do the armor numbers reflect against the vanilla values? Same with weapons.

**Comment by cyilin** [comment]
Added new commands `/rpgitem [item] additemflag [ItemFlag]` and `/rpgitem removeitemflag [ItemFlag]`
vaild item flags: `HIDE_ATTRIBUTES`, `HIDE_ENCHANTS`, `HIDE_UNBREAKABLE`
you can use `/rpgitem [item] additemflag HIDE_ATTRIBUTES` to hide the vanilla armor/weapon attributes
