### ISSUE TITLE
关于 Mythicmobs 的掉落系统

### ISSUE THREAD

**Issue by LucKyFaiL** [NyaaCat/RPGitems-reloaded#158]
可否与 Mythicmobs 此插件连系 ? 因为我用这个插件自制了一些boss或怪物 , 但是 Mythicmobs 只可设定一些 vanilla 的掉落物 , 已不可设定 RPGitems 插件的物品
Mythicmobs :   https://www.spigotmc.org/resources/mythicmobs.5702/

**Comment by phoenixlzx** [comment]
有一个比较 hack 的方式。

RPGitem 实际是在物品名称和第一行 lore 前面加一些 formatting code

所以只你需要在物品名称和第一行 lore 前面加上和希望掉落的 RPGitem 一致的 formatting code 就可以。玩家捡到该物品即可自动更新成有效的 RPGitem

**Comment by LucKyFaiL** [comment]
例如我有一个RPGitem名为stone_sword,那我是否把它改为RPGitem:stone_sword然后再放进config里?

**Comment by phoenixlzx** [comment]
你要写 `&0&0&0&0&l&b...stone sword` （举例，每个物品前的 ID 都不一样，不要照抄

前面的这串可以把 RPGitem 放在铁砧里看到，每个字符都是一个 formatting code。

同样 lore 也要加类似的 mark。当然如果你的服务器不允许玩家随意改物品名称的话，也可以在 config 里把 `bypassLoreMark` 设置为 `true`
