### ISSUE TITLE
Power help error

### ISSUE THREAD

**Issue by Taiterio** [NyaaCat/RPGitems-reloaded#16]
When using /rpgitem [item] power [power], where power requires additional arguments, the help message for the power will spam the word "power", with the powers name inbetween.

**Comment by RecursiveG** [comment]
Not quite sure why the original author did this. A quick patch.
Maybe a rewrite of command system needed in the future?

**Comment by Taiterio** [comment]
The command system is quite obstrusive in comparison to other plugins and some commands do not make sense to have in game. For example, some commands will overflow the chat, making some information the command gives to not be readable...
