### ISSUE TITLE
Could not pass event PrepareItemCraftEvent to RPGITEMS

### ISSUE THREAD

**Issue by iamawesomebro** [NyaaCat/RPGitems-reloaded#160]
While it doesn't seem game breaking it does spam the hell out of the console on making a custom recipe.

http://pastebin.com/v4ftdn4h

**Comment by RecursiveG** [comment]
It seems you've set the wrong chance of item recipe.
Please use `/rpgitem {itemName} recipe 1` to correct the chance value.
Or use `/rpgitem {itemName} removerecipe` to remove the item recipe.

**Comment by iamawesomebro** [comment]
Well if you look at the docs the whole "chance" thing was suppose to be
removed, but I went online and was told to set it to 0 so that it has 100%
chance? Quite frankly I'm not sure what the whole chance thing is about
since it's not even in the docs.
