### ISSUE TITLE
Critical, multiplication of stackable RPG items 

### ISSUE THREAD

**Issue by xxBoWiExx** [NyaaCat/RPGitems-reloaded#161]
Hi, A user found a bug very critical, when you use a stackable item as a RPG Item, it can be mutiplied.

Below, i will explain the bug.

First of all you have to:
1 . stay side of a chest
2. full your inventory with any item plus a stack of the "stackable RPG item"
3. put only one "stackable RPG item" in the chest (as shown on the picture)

[https://gyazo.com/ed7a8bc013c7c8195c63c70b6f12a076](url)
[https://gyazo.com/fec5bfbc94868f12c3edd977a9ca817f](url)

Steps:

1. Open the chest and press crtl q in order to drop the stack (in this case 63 items) and quickly take the item in the chest and put it in your inventory

[https://gyazo.com/29a9dd23928dbe3d34eb2edf34836aff](url)
[https://gyazo.com/1c8372517c9fa654058898f406ca4148](url)

2. In a few seconds (or miliseconds) will appear a stack of items

[https://gyazo.com/5e40052e57984df93ae2a934a08e3b2d](url)

3. But the droped items still remain on the floor

[https://gyazo.com/e742672a959b98fb036bdf67161c5d7c](url)

4. So now, there are 2 stacks of items

Regards

**Comment by RecursiveG** [comment]
I'm pretty sure this bug has been fixed a long time ago.
I followed your instruction but no duplication occurs.
Could you please check your plugin version by command `/rpgitem version`?
The latest release can be found [here](https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.10-v3.5.139).

**Comment by xxBoWiExx** [comment]
i use the version 3.5.139, this is a video 

[https://www.youtube.com/watch?v=GneyJz6okS4](url)

**Comment by xxBoWiExx** [comment]
i use te version 3.5.139

this is a video https://www.youtube.com/watch?v=GneyJz6okS4

regards,

**Comment by RecursiveG** [comment]
It should have been fixed in [v3.5.141](https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.10-v3.5.141)
Feel free to close this issue if you're satisfied with this solution.
Thank you for the detailed report.

**Comment by XeroZon** [comment]
Could I get a backport to 1.7.10 ;)
