### ISSUE TITLE
RPG Items for 1.8 versions, Item Duplicacion Fixed in Last version

### ISSUE THREAD

**Issue by xxBoWiExx** [NyaaCat/RPGitems-reloaded#165]
I was wondering if the Item Duplication was fixed  for the 1.8 version ? because was fixed in the last one (3.5.141) or that version can be used in 1.8?

**Comment by RecursiveG** [comment]
No, old versions are not intended to be maintained.

**Comment by RecursiveG** [comment]
This patch is backported to 1.8.
https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.8-v3.5.149
