### ISSUE TITLE
-/rpgitem [Name] create Not Work

### ISSUE THREAD

**Issue by jonas2070** [NyaaCat/RPGitems-reloaded#166]
i make the command /rpgitem icecard create and this error message come in console
INFO:1.10 Server Version v3.5.141 (1.10 Branch)

16.10 21:19:37 [Server] INFO Sharawayy issued server command: /rpgitem icecard create
16.10 21:19:36 [Server] WARN ... 21 more
16.10 21:19:36 [Server] WARN at think.rpgitems.Handler.createItem(Handler.java:87)
16.10 21:19:36 [Server] WARN at think.rpgitems.item.ItemManager.newItem(ItemManager.java:186)
16.10 21:19:36 [Server] WARN at think.rpgitems.item.RPGItem.<init>(RPGItem.java:115)
16.10 21:19:36 [Server] WARN at think.rpgitems.item.RPGItem.rebuild(RPGItem.java:379)
16.10 21:19:36 [Server] WARN Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.meta.ItemMeta.spigot()Lorg/bukkit/inventory/meta/ItemMeta$Spigot;
16.10 21:19:36 [Server] WARN at java.lang.Thread.run(Thread.java:745)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:550)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:646)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:360)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:690)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
16.10 21:19:36 [Server] WARN at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16.10 21:19:36 [Server] WARN at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:9)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(SourceFile:37)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1156)
16.10 21:19:36 [Server] WARN at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1296)
16.10 21:19:36 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:625)
16.10 21:19:36 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140)
16.10 21:19:36 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
16.10 21:19:36 [Server] WARN at think.rpgitems.Plugin.onCommand(Plugin.java:130)
16.10 21:19:36 [Server] WARN at think.rpgitems.commands.Commands.exec(Commands.java:186)
16.10 21:19:36 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:497)
16.10 21:19:36 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16.10 21:19:36 [Server] WARN at sun.reflect.GeneratedMethodAccessor326.invoke(Unknown Source)
16.10 21:19:36 [Server] WARN java.lang.reflect.InvocationTargetException

**Comment by RecursiveG** [comment]
Are you running CraftBukkit or Spigot?
RPGItems requires Spigot to operate.

**Comment by jonas2070** [comment]
Oh okay i change to spigot
