### ISSUE TITLE
Enchants and Particles

### ISSUE THREAD

**Issue by EthanRPro** [NyaaCat/RPGitems-reloaded#172]
Hey! I'd like to request some features thanks!

Ability to enchant items
Ability to then hide those NBTflags, so the item remains enchanted but the enchantment cannot be seen (This would stop the enchantment from pushing all the lore down a line and making the item look strange)
Add powers to trigger sounds and particles - RPGs have spells, spells need flashy particles and sounds

I'm currently working on an RPG server, but I cannot have spells or glowing enchanted items when using this plugin, I would love to be able to fully support my RPG server with RPGItems

Thanks!

**Comment by Librazy** [comment]
We can clone enchant from items now and we have power particle and particletick
