### ISSUE TITLE
Enchantment Issue

### ISSUE THREAD

**Issue by vipbrian** [NyaaCat/RPGitems-reloaded#177]
when I use the enchantment command

/rpgitem [Item] enchantment clone 

it doesn't put the enchantment on that item

and I'm using an item with the amount of enchant I want

**Comment by SoySaucy** [comment]
Did you enchant the rpgitem itself, then clone that specific one?
It wouldn't work if you use something like an enchanted book to clone....
P.S. when you put enchantment on the rpgitem that you're trying to clone, just use /enchant
