### ISSUE TITLE
新特性: power commandhit && power consume [right/left] 

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/RPGitems-reloaded#178]
## power  commandhit && [console_log]

 和potionhit类似，只是command对象指定为被攻击的怪物/玩家,击中触发。可以通过匹配指定被攻击实体当前位置<hitplayer.x><hitplayer.y><hitplayer.z>以及面朝向<hitplayer.yaw><hitplayer.pitch>名字<hitplayer.name>等等，以及加入攻击者的相关<player.x><player.y><player.z><player.yaw><player.pitch><player.name>
以及command指令希望增加一个参数[console_log]用于更改执行指令时候的console输出（比如setblock的时候玩家聊天窗口会提示"成功放置"，就这个。。。）

## power consume [right/left/hit] 

左键触发consume消耗掉物品&&击中消耗掉

**Comment by Librazy** [comment]
https://github.com/NyaaCat/RPGitems-reloaded/pull/181 commandhit在这里
power consume [right/left/hit] WIP

**Comment by Librazy** [comment]
https://github.com/NyaaCat/RPGitems-reloaded/pull/191

**Comment by Librazy** [comment]
console_log暂时搞不定了
