### ISSUE TITLE
About item's damage

### ISSUE THREAD

**Issue by pokpok2006** [NyaaCat/RPGitems-reloaded#179]
I hope I can remove the item damage of the item.Since the damage system will affect skillapi's skill damage.If     
I set the item damage to 20 and I hold the item on hand.The skill will deal 20 damage instead of the damage of the skill.I tried to set the item damage to 0 and it will make the skill deal 0 damage.

The version I am using is thermos 1.7.10 and rpgitem v3.5.134

**Comment by Librazy** [comment]
In v3.5.207 for 1.11.2, use /rpgitem item damageMode, set it to vanilla mode. You can use NBT attribute modifier to change its damage then.
Backport of this feature not planed yet.
