### ISSUE TITLE
Items can't be stacked

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#18]
Items such as paper can't be stacked any more in version 3.5.29. The previous version in use is 3.5.8.

Also, durability bar displayed many times takes up too much screen space in item tooltip box.

**Comment by phoenixlzx** [comment]
Further test found that when an item configured with durability, each use will add a line to the durability bar, make the item unbreakable.

**Comment by Taiterio** [comment]
I corrected the bug that caused the durability bar to stack infinitely in commit 7f90c4c2b956b72682719c92e9be444423413572. While doing that, I also noticed that the code for setting the durability of an item is utterly broken and needs alot more work. Did this bar work before or was it a result of one of my earlier commits?

**Comment by phoenixlzx** [comment]
Durability worked as usual in v3.5.8. For the latest commit i tried but it does not work yet - the durability bar does not decrease while using the item.

**Comment by Taiterio** [comment]
Fixed this issue in commit 6f6c8a48b2de7c67ebdfb7f6d8dce76f46a9785c. The problems stemmed from commit a1824a8edb01b941247ef65527eb28e451dec3a9. It seems like the RPGItems class depended on the getLocaleMeta() function returning a clone of the itemmeta, not the itemmeta itself.

**Comment by phoenixlzx** [comment]
Found another issue - When using items with durability, the whole stack item durability decreased.
