### ISSUE TITLE
Potion tick on speed for a weapon and armour won't work

### ISSUE THREAD

**Issue by Enoceant** [NyaaCat/RPGitems-reloaded#183]
I am adding weights into my server, only on the weapons and armour though.
So I made a armour that gives 2 speed while in use/ equipped
And I made a weapon/sword that gives -1 speed while in use
These powers are all potion ticks.
So I equipped the armour and walked a bit and was quite fast
So I held the weapon but the speed didn't change.
Is there another way to do this, 
Or can it be fixed
So like armour adds 2 speed and weapons takes away 1 speed so that will equal to 2-1 equals 1.
I would like something like that.
Also if it would be possible as to change the "gives speed -2 while in use" to "takes 2 speed while in use"

**Comment by Enoceant** [comment]
So I basically want all the speed robe measure up

**Comment by Librazy** [comment]
To apply the same effect multiple times is not possible. It is an Minecraft feature.

PotionTick with amplifiers can sum up can be an rpgitem feature but you may need to wait a few weeks...

**Comment by Enoceant** [comment]
Yes, thanks a lot. Will that fix my problem? Like if I had a speed 5 armour and a -2 speed sword will that make it 3 walk speed for the player

**Comment by Enoceant** [comment]
This is my most favourite item plugin for rpg there is nothing better that has all these features

**Comment by Enoceant** [comment]
can you also tell me if the messages are also changeable " gives -2 speed" into"
"[-2] speed" and "[+3] speed"
I haven't tried out life steal or health boost. I would also like to change them into
"[-20] health" and "[+15] health" also like a list and categories of the powers/ effects such as like this.

When adding luck does that mean when you kill a mythic mob you will get more of the items in the loottable or is it not included.

Will attack speed also be added.

Stats:
[+40] Health
[+50] Damage
[-2] Speed
[+9] Armour
[+5] Attack Speed

Powers:
Life steal - (activation)
10% Luck

Something along those lines. In this order if you can. Thanks, best of luck to continuing this plugin and making it way better than other item plugins. :smile:

**Comment by Enoceant** [comment]
The equip or hold item to apply effects wouldn't need to be put on there.
