### ISSUE TITLE
Can we have the ability to change the attack speed of some items?

### ISSUE THREAD

**Issue by Thaumcraft4Lyfe** [NyaaCat/RPGitems-reloaded#184]
You shouldn't have to use the potiontick power to change the attack speed of an item. A new command should be added.

/rpgitem [Item] hitspeed [integer]

The attack meter would recharge according to the integer in ticks. Putting 0 or -1 would remove the attack cooldown completely.

**Comment by Enoceant** [comment]
Oh thanks a bunch

**Comment by Librazy** [comment]
Use /rpgitem item damageMode, set it to vanilla mode. You can use NBT attribute modifier to change its damage and speed then.
