### ISSUE TITLE
Please, add potiontick power that sum up

### ISSUE THREAD

**Issue by Enoceant** [NyaaCat/RPGitems-reloaded#185]
Can you please add a feature
Where the rpg item and rpg armour you are currently wearing, which has a potiontick power on it for example
Speed 2 on item,
Speed -3 on armour, 
In my server this is basically weight of the armour, for warriors, they wear this armour but give a lot of defence.

So if they equip this armour and item, I would like it to sum up, like:
Speed 2 - 3 = -1

**Comment by Librazy** [comment]
duplicate #198
