### ISSUE TITLE
Please add compatibility with skillapi level req

### ISSUE THREAD

**Issue by Enoceant** [NyaaCat/RPGitems-reloaded#186]
Basically I want this plugin to be compatible with skillapi,
So that it can have skillapi requirements
Such as:
Class requirement
Class Lvl requirement
Skill requirement
Excluded class - this item can be used with all classes except for this one

Format in the lore of the RpgItem:
Requirements:
Skill: (needed skill)
Lvl: (needed lvl)
Class: (needed class)
Unusable: (excluded class)

Or any good name for unusable, also this requirements category won't show up unless it is needed

**Comment by Librazy** [comment]
duplicate  #119
