### ISSUE TITLE
[Bug] Attack Cooldown damage reduction doesn't work.

### ISSUE THREAD

**Issue by Thaumcraft4Lyfe** [NyaaCat/RPGitems-reloaded#187]
In 1.9+, an attack cooldown was put in place so that you have to wait a set time otherwise the damage of your attack will be reduced. This plugin has no scaling damage depending on attack cooldown, meaning if you wanted to make an item that hit hard but had a slow attack speed it wouldn't matter.

**Comment by Librazy** [comment]
Use /rpgitem item damageMode, set it to vanilla mode. You can use NBT attribute modifier to change its damage then.
