### ISSUE TITLE
power aoecomand

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/RPGitems-reloaded#189]
- ## command：

/rpgitem xxxxx power aoecommand [cooldown] [selector:type=[player|entity|block|air],r=[number],rm=[number],facing=[0-180]c=[number]] [left/right] [display] [command] [permission]

- ## selector:选择器参数意义：

类似@e[name=xxx,r=xx,c=xx]之类原版选择器，不同的是希望可以选择方块

type(类型)：玩家|实体|方块|空气

r&&rm(范围半径)：r为小于r的作用半径内，rm喂大于r的作用半径内，两者都填的话就取交集，都填情况下rm不能大于r，出于安全考虑rm不能单独存在

facing(视角范围)：当前水平视角+-参数值所选取的扇形区域

c(数量)：最大选取的个数

- ## 效果

效果为，检测所有在选择器选择范围内的玩家/实体/方块/空气，并对每一个选取得到的对象执行一次command参数所配置的指令，例如：
/rpgitem xxxx power aoecommand 1 [type=block,r=10,rm=10,facing=90] right `xxx` `/summon creeper ~ ~1 ~ {ignited:1,Fuse:0}` minecraft.command.sumon
在你面朝的正前方半圆位置的半径为10处的方块上方一格放置一圈立刻引爆的苦力怕
再或者：
/rpgitem xxxx power aoecommand 1 [type=entity,r=10,rm=2] right `xxx` `/summon arrow ~ ~20 ~ {Motion:[0.0,-2.0,0.0],pickup:0,damage:20}` minecraft.command.sumon
对你周围大于2小于10半径以内的所有实体头上降下箭雨

----------------------------------------------

顺带，把commandhit和command里边可解析的参数统一一下。。。
以及加个commandhit里边攻击者和被攻击者之间互相相对yaw和pitch

**Comment by Librazy** [comment]
- [ ] Entity
- [ ] Players only
- [ ] Mobs&animals only
- [ ] Blocks
- [ ] Surface
- [ ] Air
