### ISSUE TITLE
Power AOE

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#19]
Area of effects of potions will be a great power to add. When activated, the potion effects can be applied to all entities in a custom range for a specified time from the center player.

An option to decide whether the effect will apply to the player using this item will be better I think.

**Comment by Taiterio** [comment]
Sounds great! So for creating the power, would the command "/rpgitem ... aoe <PotionType> <Range> [SelfApplication (default true?)]" fit?

Furthermore, should the Bukkit names for potions be used or should a function be added that resolves them to their real names or potentially even to those found in the locale?

**Comment by phoenixlzx** [comment]
I think the range variable should be added too.
Full command `/rpgitem [item] aoe [potion effect] [area range] [duration] [SelfApplication]` will be good.

There's already a wiki page for potion names [here](https://github.com/NyaaCat/RPGitems-reloaded/wiki/Potion-Effects)

**Comment by Taiterio** [comment]
Seems like I had deleted the other arguments in my earlier comment, this was the command I was going for aswell :)
