### ISSUE TITLE
[Feature Request] Custom item model

### ISSUE THREAD

**Issue by kyakou** [NyaaCat/RPGitems-reloaded#197]
Hello! Would you be willing to add support for textures by item durability/damage? Thanks!

**Comment by SoySaucy** [comment]
I believe that will greatly increase the versatility of this already amazing plugin, I am sure many people other than myself are looking forward to this addition.....

加油加油! Developers <3

**Comment by cyilin** [comment]
added new command `/rpgitem [item] customItemModel`

Example (make sure you have load a resource pack): 
1. `/rpgitem test create`
2. `/rpgitem test give`
3. enable custom item model support `/rpgitem test customItemModel`
4. set item textures and durability value (damage value) `/rpgitem test item wood_hoe 10` 
5. `/rpgitem test additemflag HIDE_UNBREAKABLE` if you want to hide the "Unbreakable" attribute. (see #157)

**Comment by Vyrgax** [comment]
Hey, I tried doing this, and the texture triggers, but only when customItemModel is disabled. If it's enabled, then I just get the item with max durability, so without texture. But when it's disabled, though, durability still is a thing, so it'll eventually break.

**Comment by cyilin** [comment]
@Vyrgax you may need to set `damaged` to 0 for unbreakable item. like this: https://github.com/elBukkit/MagicPlugin/blob/master/Magic/src/resource-pack/default/assets/minecraft/models/item/wooden_hoe.json#L8
