### ISSUE TITLE
Posibility of Health Boost in potiontick

### ISSUE THREAD

**Issue by apflu** [NyaaCat/RPGitems-reloaded#202]
It is possible to increase the maxinum health with the potion effect health boost.
But I can't find Health Boost in https://github.com/NyaaCat/RPGitems-reloaded/wiki/Potion-Effects
So is it possible to use it? #141

**Comment by Librazy** [comment]
There is health_boost, but it is broken in potiontick because potiontick will refresh the effect sometimes and you will lost your extra health during refreshing.
Trying to fix it.
