### ISSUE TITLE
power potionloop && set cost lock

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/RPGitems-reloaded#208]
## power potionloop

类似potiontick，指令/rpgitem [item] power potionloop [Duration] [Amplifier] [Effect]

- Duration:持续时间
- Amplifier:效果等级
- Effect：效果

## set cost lock [value]

能量锁，设置这个锁的值之后 该道具的一切能量消耗必须在能量大于锁的值以上才可以使用，否则等同于能量不足。

**Comment by Librazy** [comment]
- [ ] set cost lock  1.11-v3.5.203的durabilitybound
- [ ] power costcommand 
- [ ] power potionloop
