### ISSUE TITLE
Rewrite the `RPGMetadata` mechanism

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/RPGitems-reloaded#21]
Currently, RPGMetadata storaged in lores of items in form of formatting code, which is costly and inefficient.
Considering moving this into NBTTags of items.
This may require additional libraries and increase incompatibility between versions.

**Comment by phoenixlzx** [comment]
Another thing you need to pay attention to is the items distributed to players, which may not work after such change.

**Comment by Taiterio** [comment]
Rewriting the RPGMeta to write to an item's NBTTag instead. Also adding a handler for when the old format is found, which transforms the old data to the new format. Furthermore, to allow version compatibility I'd suggest loading the methods needed to alter the nbttags when the class RPGMetadata is created via Reflection.

**Comment by phoenixlzx** [comment]
The transform method should have a config option, otherwise players could still duplicate more items and then transforms it into new valid items.

**Comment by Taiterio** [comment]
It seems like custom NBT tags are not an option as any update to an items metadata will delete them... 

Another way to rewrite this would be to keep the data stored in memory for the duration of the server's uptime and then just save the data to the lore when the server shuts down. The problem with this method would be that there are major problems in the sense of the effort needed to track items and server crashes destroying the items.

**Comment by phoenixlzx** [comment]
However NBTTags seems the best way to solve this issue, those plugins delete original NBTTags may also not compatible with RPGItems. We could track GitHub issues if any server admin run into this situation.

**Comment by RecursiveG** [comment]
@phoenixlzx A possible problem when using NBT to store date is it may become difficult for other plugins to spawn rpgitems which now can be easily spawned by setting lores. Extra APIs may be needed.

**Comment by phoenixlzx** [comment]
@RecursiveG Currently it stores in names, like `&0&0&0&3&1&a&fA wonderful name`
So players with rename permission could easily duplicate an item.

What about store both in names and lores? Should be more choices for permissions.

**Comment by RecursiveG** [comment]
Will be solved with #34
