### ISSUE TITLE
power costparticle && power costcommand

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/RPGitems-reloaded#210]
## power costparticle

指令： power costparticle  [Interval] [Cost] [Contrast] [VisualEffect]

描述：一个可以监听能量条阈值持续触发的粒子效果，用于代替某些需要特别随时关注能量是否满了的道具以及部分特殊用途

- Interval:触发间隔（游戏刻）
- Cost: 触发阈值
- Contrast: 触发阈比较值，例如大于阈值、小于阈值或者等于阈值触发
- VisualEffect:粒子效果( ~尽可能多~ )

## power costcommand

指令/rpgitem [item] power costcommand [Cooldown] [Cost] [Contrast] [Delayed] [Display] [Command] [Permission]

command类指令，触发方式为cost的阈值，例如大于或者小于某个设定好的阈值时则触发一次指令( ~或者大于|小于|等于某个值时候持续触发某个指令的刷屏机器~ )

- Cooldown:冷却时间
- Cost:能量阈
- Contrast:触发阈比较值，例如大于阈值、小于阈值或者等于阈值触发
- Delayed:延迟，一般写0，如存在则延迟触发指令
- Display:指令技能名称
- Command:指令字符
- Permission:权限节点

**Comment by Librazy** [comment]
我的内心毫无波动，甚至有些想静静

**Comment by miu-wen** [comment]
想要静静，回头送你几十只。。。- -

**Comment by Librazy** [comment]
Have better approach now
