### ISSUE TITLE
Vanilla Item descriptions

### ISSUE THREAD

**Issue by MurderGizmo2013** [NyaaCat/RPGitems-reloaded#216]
![image](https://cloud.githubusercontent.com/assets/26947458/24734218/2b97810a-1a4a-11e7-9a07-e620e03adc44.png)
I'd like to know if there is a way to remove the When held in main hand: text in grey. I've tried seemingly every command and havent seen anyone else with this question, so i must be missing something. Hoping this is the place to get a response. Thank you very much

**Comment by cyilin** [comment]
See #157
