### ISSUE TITLE
[Help] Enchantment troubles

### ISSUE THREAD

**Issue by lilbudgotswag** [NyaaCat/RPGitems-reloaded#219]
Hello! I am trying to enchant custom weapons that I make with this plugin however once enchanted the enchantments that I try to use don't affect the damage of the weapons. 
I made a rpgitem with a base damage of 10 and put 2 in my inventory. One with no enchantments and one with sharpness 2. The screenshots are below and as you can see the damage doesn't change. 
Is there a fix for this?

![2017-05-06_09 26 47](https://cloud.githubusercontent.com/assets/13305459/25774096/40eaecde-323e-11e7-995c-fb01e4206192.png)
![2017-05-06_09 26 51](https://cloud.githubusercontent.com/assets/13305459/25774097/41ee5b52-323e-11e7-95f7-b22ac4827ab5.png)
![2017-05-06_09 26 58](https://cloud.githubusercontent.com/assets/13305459/25774099/430acff2-323e-11e7-811a-5b97021c4093.png)
![2017-05-06_09 27 22](https://cloud.githubusercontent.com/assets/13305459/25774100/4428f85a-323e-11e7-90af-ee30d4aa8b3c.png)

**Comment by Librazy** [comment]
RPGItem's damage (in "fixed" damage mode) won't be affect by enchants. It's a feature now. 
However, if you use [newest version ](https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.11-v3.5.214), you can use "additional" damage mode by `/rpgitem item damageMode` twice (until it says "damage mode set to additional damage (vanilla minecraft damage plus RPGItem damage)"), the damage it made will be the damage you set plus a damage done by a enchanted wooden sword,14(without enchant) vs 15.5(with Sharpness II)  in your case.
