### ISSUE TITLE
Problem with PvP System

### ISSUE THREAD

**Issue by ungermum** [NyaaCat/RPGitems-reloaded#220]
Hello, I've spotted that starting from vertion 209 of PRGItems PVP-system doesn't work correctly, meaning that there is no cooldown for all of the weapons. Is there a way you can fix this problem? Best regards, (TushinoCraft project).

**Comment by ungermum** [comment]
UP!

**Comment by ungermum** [comment]
hey!

**Comment by Librazy** [comment]
We need more detail. What does it mean by "no cooldown"?
