### ISSUE TITLE
/rpgitem [item] durability LAG :'( 

### ISSUE THREAD

**Issue by LicorneCosmique** [NyaaCat/RPGitems-reloaded#222]
Hi, 
When i set the durability of a chain_helment to 999 and i give it to me. The durability is set to 0... That mean it break instantly. I did something wrong or the plugin is laggy with chain stuff ?

**Comment by LicorneCosmique** [comment]
I'm on 1.11.2 btw

**Comment by Librazy** [comment]
Use /rpgitem item defaultdurability 999 to set default durability (the durability of new item).

**Comment by Librazy** [comment]
There seems to be some bug about the default value of default durability but I haven't sort it out yet.

**Comment by LicorneCosmique** [comment]
Thanks god you solved my problem ! You are awesome. Thanks mate. But i have another question, there is a way to take less damage with a chainmail stuff than a diams stuff ?

**Comment by Librazy** [comment]
If you means vanilla armors, you can use some NBT edit plugin to add a [attribute modifier](http://minecraft.gamepedia.com/Attribute#Vanilla_modifiers) to chainmail stuff that add some generic.armor to it.
Of RPGItem armors, you can simply give chainmail more armor.

**Comment by LicorneCosmique** [comment]
Nop i'm sorry in fact it make my chain helmet unbreakable. The default vanilla durability is 165, i had set it to 170 just for the test and it doesnt loose any durability. Sometimes it go to 163 go up to 164 and get back to no damaged helmet...
