### ISSUE TITLE
请问PowerCommand类如何使用

### ISSUE THREAD

**Issue by ExcitedFrog1s** [NyaaCat/RPGitems-reloaded#225]
我的插件里有这样一段代码：       
 RPGItem item09=new RPGItem("LotteryItem09",1009);
        item09.setItem(Material.NAME_TAG);
        item09.setDisplay("代币包（小）");
        item09.setQuality(Quality.UNCOMMON,true);
        item09.addDescription("一个小小的代币包。");
        PowerCommand tokenPowerA = new PowerCommand();  //点券效果1
        tokenPowerA.command="money give " + player.getName() + " 188";
        tokenPowerA.permission="iConomy.accounts.give";
        tokenPowerA.display="§b 左键使用获得188代币（token）。";
        tokenPowerA.isRight = false;
        item09.addPower(tokenPowerA);
        item09.addPower(consume);
        inventory.setItem(9,item09.toItemStack());//塞进9号格子
当我从inventory里面拿出这个物品之后，左键，没有任何的反应。
请问应该对这段代码作何更改呢？

**Comment by Librazy** [comment]
目测是Power没有绑定到物品。每个power实例应唯一的属于某个RPGItem。
```
tokenPowerA.item = item09;
consume.item = item09;
```
（目前也在考虑RPGItem.addPower里添加`power.item = this`）

**Comment by ExcitedFrog1s** [comment]
我添加代码后，仍然不行，而且之前没有任何的报错。这是为什么呢？

**Comment by ExcitedFrog1s** [comment]
跪求dalao解答
