### ISSUE TITLE
PowerCommand绑定（也许）到物品后仍无法使用

### ISSUE THREAD

**Issue by ExcitedFrog1s** [NyaaCat/RPGitems-reloaded#229]
`                   RPGItem item09=new RPGItem("LotteryItem09",1009);
                    item09.setItem(Material.NAME_TAG);
                    item09.setDisplay("代币包（小）");
                    item09.setQuality(Quality.UNCOMMON,true);
                    item09.addDescription("一个小小的代币包。");
                    PowerCommand tokenPowerA = new PowerCommand();  //点券效果1
                    tokenPowerA.command="/money give " + player.getName() + " 188";
                    tokenPowerA.permission="iConomy.accounts.give";
                    tokenPowerA.display="§b 右键使用获得188代币（token）。";
                    item09.addPower(tokenPowerA);
                    tokenPowerA.item=item09;
                    PowerConsume consume09 = new PowerConsume();
                    item09.addPower(consume09);
                    consume09.item=item09;
                    player.getInventory().addItem(new ItemStack[]{item09.toItemStack()});
`
在游戏中获取物品后，能看到“Consume on use”、“右键使用获得188代币（token）。”等字样，但是右键无反应。后台并没有任何报错。
求解……

**Comment by Librazy** [comment]
RPGItems 目前并没有考虑对其他插件调用的兼容性，如果有兴趣针对RPGItem做二次开发请固定版本并且自行调试
