### ISSUE TITLE
 Users having the RPGITEM becomes normal

### ISSUE THREAD

**Issue by xGame324** [NyaaCat/RPGitems-reloaded#230]
When I have op the item works and everything but when I put the user the item becomes normal

OP: http://i.imgur.com/Mo7USf2.png

NO OP LEGEND: http://i.imgur.com/NMLnWAa.png

**Comment by Librazy** [comment]
May be caused by some other plugin. If this issue still exist, please provide your server version and other plugins and console output if needed.
