### ISSUE TITLE
Potionhit effects other players in non pvp zones

### ISSUE THREAD

**Issue by lilbudgotswag** [NyaaCat/RPGitems-reloaded#231]
Title explains most. People on my server can give other players potion effects if they hit them with an rpgitems weapon with potion hit even if the area is non pvp. This is a really big issue for me i'd strongly appreciate if it got fixed soon.

**Comment by Librazy** [comment]
What version are you using? I believe that it was fixed in 1.11 branch


_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by lilbudgotswag** [comment]
I'll try reinstalling it but it is 1.11 branch

**Comment by lilbudgotswag** [comment]
If you're seeing this another issue I have is that I can't find a way to repair any rpgitems. For all my rpgitems i've set the default durability and durability to the same thing is that the problem?

**Comment by Librazy** [comment]
RPGItems are unrepairable now but you may have some power that increase durability.
