### ISSUE TITLE
能否加入合成表功能的物品NBT检查

### ISSUE THREAD

**Issue by StarWishsama** [NyaaCat/RPGitems-reloaded#232]
加入一个类似于 CustomNPC Mod 的功能，我认为这个功能十分实用。

**Comment by MlgmXyysd** [comment]
现在合成表貌似扔进去RPGitem物品可以直接用原版物品合成

**Comment by Librazy** [comment]
这应该是Spigot的合成表的问题，以后可能会加相关的功能但目前不影响正常使用。
duplicate #262
