### ISSUE TITLE
Mythicmobs damage skill broken, damage() function doesn't take into account rpgitems armor

### ISSUE THREAD

**Issue by getthegun** [NyaaCat/RPGitems-reloaded#234]
Rpgitems: 3.5.231
Spigot: 1.11.2

So I have a projectile skill and when it hits it gives the player damage through the damage skill.
`  NecromancerShot1:
    Conditions:
    - hastag{tag=NecroPhase1} true
    - offgcd
    Skills:
    - projectile{onTick=NecromancerShot1-Tick;onHit=NecromancerShot1-Hit;v=15;i=1;hR=1;vR=1}
  NecromancerShot1-Tick:
    Skills:
    - effect:particles{p=smoke;amount=20;speed=0.2;hS=0.1;vS=0.1} @origin
  NecromancerShot1-Hit:
    Skills:
    - damage{a=35;ignoreArmor=false}
    - potion{type=BLINDNESS;duration=60;lvl=0}`

But even if I wear rpgitems armor that should give me 100% armor, it does 35 damage as if I were wearing none. Is there a workaround for this because I really need projectile skills to deal proper damage to my players, thanks. 

I even commissioned someone for a /damage plugin that will damage the player when run, as a workaround for the broken damage skill. However, it works with rpgitems, but it accounts for normal armor as well. Let's say it was /damage player 10 and I was wearing gold armor with 16% rpgitems armor. It would do 4 damage because it takes into account vanilla minecrafts 44% armor on gold armor, as well as the 16% rpgitems armor.

I need this feature to work very quickly and I will pay somebody a large amount to get it working. I left the custom damage command plugin below if you want to try and fix the problem with that one. I really need this done ASAP so help would be very much appreciated, thanks.

(I will pay anyone who fixes this issue $15.)

[DamageCommand v1.0.4.zip](https://github.com/NyaaCat/RPGitems-reloaded/files/1107433/DamageCommand.v1.0.4.zip)

EDIT: It has something to do with the fact that the damage() method provided by Spigot doesn't seem to take into account the armor values added by rpgitems

**Comment by Librazy** [comment]
won't fix for main plugin.
