### ISSUE TITLE
Durability state ?

### ISSUE THREAD

**Issue by Nariko13** [NyaaCat/RPGitems-reloaded#236]
Since it is possible to add unbreakable, is it possible to add a durability state to the item (maybe it's already possible, sorry if it's the case) ? It could give the possibility to have custom item added via resourcepack working with your plugin ^^ 

Respectfully ?

**Comment by Librazy** [comment]
You may want to take a look at https://github.com/NyaaCat/RPGitems-reloaded/issues/197
