### ISSUE TITLE
Better Particle Customization ? / Bind like enchant / power

### ISSUE THREAD

**Issue by Nariko13** [NyaaCat/RPGitems-reloaded#237]
Now i am being a little too greedy, but i am asking if it is already possible to customize particle better ?

For now we can define one particle which will spawn on us, but always at the same place, with the same position of effect,

Is an other way exist to make multiple at different position, so activating a scepter effect looks better ?

EDIT : OK i think it's possible thx to the command power ! sorry for bothering but i have another question ;)

Also, anyway to give a bind enchant to some item or something like that ? like player die but keep item with him (asking this for some particular reasons)

**Comment by Librazy** [comment]
power particle now have all params available for 3.6/1.13+
