### ISSUE TITLE
創造物品時沒有任何反應

### ISSUE THREAD

**Issue by NightLame** [NyaaCat/RPGitems-reloaded#239]
例如:輸入/rpgitem op1 create 時沒有任何訊息跑出來也沒有創造出此物品....Minecraft 1.11.2 RPGItem-reloaded-1.8-v.235

**Comment by phoenixlzx** [comment]
1.11.2 不要用 1.8 的版本，用这个 https://github.com/NyaaCat/RPGitems-reloaded/releases/download/1.11-v3.5.231/rpgitem-reloaded-1.11-v.231.jar

**Comment by NightLame** [comment]
我已改,但輸入出現 /rpgitem help Terms[String]
Shows commands and help for commands that contain the search terms [Terms]
