### ISSUE TITLE
Potential unauthorized item duplication

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/RPGitems-reloaded#24]
The formatting code storage in lores and tooltips may be modified by other plugins.
Making it possible to perform unauthorized item modification/duplication.
A possible solution may be #21

**Comment by Taiterio** [comment]
Moving the data to nbttags should resolve the issue of *accidental* modification of the item data, it would however still be possible for other plugins to alter this method of storage aswell.

**Comment by phoenixlzx** [comment]
This issue should be solved ASAP. We will publish announcements about the changes especially this version will not compatible with previous versions.
