### ISSUE TITLE
技能觸發問題

### ISSUE THREAD

**Issue by NightLame** [NyaaCat/RPGitems-reloaded#246]
當設定武器為消耗品時,右鍵使用後物品消失就無法觸發技能....還有當射出箭矢在命中目標前切換手持物品,也無法觸發技能...而射出的箭矢可以撿取,這將變成一個無限箭矢的問題
 版本: spigot 1.11.2
rpgitem: rpgitem-reloaded-1.11-v.231
令問
例: /rpgitem item1 drop zombie 機率
請問機率要如何設置
雙精度浮點是什麼?

**Comment by Librazy** [comment]
fixed
