### ISSUE TITLE
当失去一件防具的穿戴权限后会发生什么

### ISSUE THREAD

**Issue by prozhong** [NyaaCat/RPGitems-reloaded#247]
我看见可以设置物品的权限，而且代码也有对应的checkPermission
如果我在拥有权限的时候穿上防具，后面失去了对应的权限
防具会自动脱下吗，还是依然穿戴着且能有效免伤？
Events.java#L583这里的处理会造成无敌吗

**Comment by Librazy** [comment]
是个问题，没有权限的话似乎会导致这个玩家无敌……Hmmm
这是一个祖传的逻辑，稍后我会思考一下如何处理比较好

**Comment by Librazy** [comment]
现在会忽略这件护甲的所有效果并且发出警告，但不会脱下它
