### ISSUE TITLE
Problem with selling items

### ISSUE THREAD

**Issue by ungermum** [NyaaCat/RPGitems-reloaded#248]
Hello. Problem with selling rpgitem items in GeneralMarket plugin. 
Cant buy item of rpgitems. 
I think, it's because lore of rpgithems.
(https://www.spigotmc.org/resources/general-market.17053/).
Video problem:  https://youtu.be/5qhJS_cd9YM
Can u fix that?

**Comment by ungermum** [comment]
so?

**Comment by Librazy** [comment]
We tried to sell rpgitems through many  market plugin and it works.
As for GeneralMarket, it is a paid plugin so you may seek help from them.

**Comment by ungermum** [comment]
@Librazy Can you give me links links to these plugin-market?

**Comment by cyilin** [comment]
@ungermum try rpgitem 1.12-v3.6.295 or 1.11-v3.5.296

**Comment by ungermum** [comment]
@cyilin YES! thank you very much!
