### ISSUE TITLE
Can't change display language

### ISSUE THREAD

**Issue by Nicklander** [NyaaCat/RPGitems-reloaded#249]
Version: rpgitem-reloaded-1.11-v.259

I can't change the display language in the locale/en_GB.lang file. I wish to put something different instead of "damage" & "armour". The settings "command.info.armour" & "command.info.damage" don't change the display language of the item.

**Comment by Librazy** [comment]
They are not controlled by the lang files but you need to change the config instead. "Armour" is defaults.armour and "Damage" is defaults.damage.
https://github.com/NyaaCat/RPGitems-reloaded/blob/1.12/src/main/java/think/rpgitems/item/RPGItem.java#L685
