### ISSUE TITLE
Translation using transifex

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#25]
I have setup the transifex project to help with translation. The project url is https://www.transifex.com/phoenixlzx/rpgitems/

The source language is `en_GB` and transifex will automatically download new version of this file from Github.

Feel free to ask for new languages and help with translation. @felixonmars @ym @RecursiveG have been invited to the maintainers team. @Taiterio once you have registered on transifex, leave me with your username and I will add you to the team.

**Comment by Taiterio** [comment]
Registered, username is Taiterio :)
