### ISSUE TITLE
AOE power [self] option not working

### ISSUE THREAD

**Issue by Nicklander** [NyaaCat/RPGitems-reloaded#250]
The [self] option is not working, the aom is applied to all players no matter what you type in [self].
/rpgitem name power aoe Poison 200 5 poison 100 0 false

Version: rpgitem-reloaded-1.11-v.259

**Comment by Nicklander** [comment]
Thanks it's fixed in v262 !
However the value for the aoe effect amplifier is wrong, it needs to be +1 ! Otherwise the effect level is "0" instead of "1".

**Comment by Librazy** [comment]
Actually amplifier for PowerAOE is a historical issue. If we fix it, we may break others' item, and it can be easily walked around……
