### ISSUE TITLE
Power rangedonly not working on bows

### ISSUE THREAD

**Issue by Nicklander** [NyaaCat/RPGitems-reloaded#253]
Players can still hit other players with rpgitem bows even tho the rangedonly power is applied on them.
I don't want the player to be able to left-click with that bow, he should only be able to shoot arrows.

Version: rpgitem-reloaded-1.11-v.262

Oh....and could you include an option to hide the "you must wait X seconds" messages on certain items ? On some items this is really annoying and should better be hidden.

**Comment by Librazy** [comment]
I'll investigate the first later.
For the second, a nice suggestion and I'm finding a better way to prompt players about cooldowns

**Comment by Formula350** [comment]
Perhaps offer a player-command *(with permission)* to toggle: `Chat Message | Action Bar | Disabled (no message)`
As well as those options to define as the default on a  per-item basis.

**Comment by Nicklander** [comment]
Ok...so I investigated this issue again and it's working better now. Apparently when using a bow with the power "rangedonly" the player only gets damaged by 1 everytime he gets hit no matter how high the bow damage originally is and no other power effects are transmitted aswell. I think the current behaviour is completely fine, maybe you could implement an option to disable the ability to attack with the bow completely but as I said, I'm satisfied as it is now.
