### ISSUE TITLE
Power deflect not working correctly

### ISSUE THREAD

**Issue by Nicklander** [NyaaCat/RPGItems-reloaded#255]
The deflect power seems to be quite buggy, most of the time it isn't working at all. You also need to modify the file manually, there's no ingame command-help for this power.

Version: rpgitem-reloaded-1.11-v.262

Thanks for fixing all those problems, they're kind of a gamebreaker. The most important issue you should focus on at the moment seems to be the one posted by Severdez about the consume problem (watch replies).

**Comment by Librazy** [comment]
Because it is too buggy to work so I didn't write document for it. And I have not found the better implement yet so I just left it as-is.

**Comment by Librazy** [comment]
Should do better now
