### ISSUE TITLE
Power ice not working properly

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGitems-reloaded#258]
The power ice shoots the iceblock and expands immediately. So it pretty much just summons the big iceblock right in front of you instead of shooting it and travelling for a few blocks

Version: rpgitem-reloaded-1.11-v.262

**Comment by Formula350** [comment]
I can confirm that this is happening with RPGItems v3.5.262 for 1.11. Even walking backwards when launching the Ice Block causes it trigger the power right in front of you.

This HAD been working fine in RPGItems v3.5.**255** for 1.11

**Comment by Formula350** [comment]
Just noticed that this was fixed in **1._12_** b275. Will this also be backported to 1.11?

**Comment by Librazy** [comment]
Actual b275 is for 1.11 https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/1.11-v3.5.275
RPGItems 3.6 (1.12) is in development (lacking some fancy prompt in command line) but should be basically usable now.

**Comment by Formula350** [comment]
Oh, crap, so it is! My apologies. I didn't even originally notice that the 275 build was skipped on 1.12, and I had been looking at b274.
