### ISSUE TITLE
Multiple Power AOE with cooldown only applies one effect

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGitems-reloaded#259]
![2017-11-03_14 52 56](https://user-images.githubusercontent.com/33037241/32377069-d9b65556-c0a6-11e7-95dc-29ca650c94ab.png)
![2017-11-03_14 52 51](https://user-images.githubusercontent.com/33037241/32377070-d9d02832-c0a6-11e7-9fcf-e4ae4ee4b383.png)

When giving a RPGItem multiple power AOE, only one effect is applied to the player. Strangely this is only the case when there is a cooldown on the aoe effects (even if every AOE power has different cooldowns).

I tested this with the [self] option activated. Once I have the possibility to test it on another player I will update this post.

Version: rpgitem-reloaded-1.11-v.262

EDIT: I attached 2 pictues showing the aoe effects on the RPGItem and the outcome when right-clicking it.
Other players also only get applied one effect.
2nd Edit: Same problem with the power potionself.

**Comment by Librazy** [comment]
Some powers' cooldown are set on the power, some are based on the effect or command the power has. Unfortunately PowerAOE belongs to the former. That is to say, when you triggered the first PowerAOE that apply blindness, PowerAOE itself start to cool down, so the second and the third PowerAOE won't work. If you only apply cooldown to the last PowerAOE, it should work as intend.
