### ISSUE TITLE
recipes with stacks  1.12.2

### ISSUE THREAD

**Issue by MyCraftServer** [NyaaCat/RPGitems-reloaded#261]
Is there a posibility to use craft recipes with stacks or more than one item?

I did the folowing recipe:

![6c8ac4a44b5a4ce49919a10b5394b542](https://user-images.githubusercontent.com/31355223/32867407-8f76ee7a-ca32-11e7-8a01-edd0c26c4d4b.png)

But can be crafted with one of each item

![c7b78bb842b18b008aae5c8e4feed360](https://user-images.githubusercontent.com/31355223/32867406-8df6514e-ca32-11e7-85ee-83c88b6efeaa.png)

**Comment by Librazy** [comment]
That is an issue of spigot's crafting system. We may add a workaround later but it is works fine now.
