### ISSUE TITLE
Problems whit atributes in recipes

### ISSUE THREAD

**Issue by MyCraftServer** [NyaaCat/RPGitems-reloaded#262]
Some armors have diferent atributes and when a player try to craft they cant because they have an item whith diferent atributes, so there is a posibility that crafting ignore all those atributes? 

![1d95ebef87bb9939849e7e975299e886](https://user-images.githubusercontent.com/31355223/32869753-3e0e87b2-ca3e-11e7-9018-5c101f2e4de6.png)
![0ac199e1c9974b285b1f3559620ee47c](https://user-images.githubusercontent.com/31355223/32869754-3eef513e-ca3e-11e7-8530-c3720ee608e0.png)

**Comment by Librazy** [comment]
That is also an feature of spigot's crafting system. We may add a workaround later but it is works fine now.
