### ISSUE TITLE
Test all power against RPGItems 3.6

### ISSUE THREAD

**Issue by Librazy** [NyaaCat/RPGitems-reloaded#266]
And deprecate some of little use

**Comment by Formula350** [comment]
If 3.6 is able to be backported to 1.11 then I can add it to my test server for my staff to play around with and determine what works and doesn't work. That'll also give you the knowledge of knowing whether a server with hundreds and hundreds of items *(my items.yml is just over 1MB)* will import smoothly or not. 

For example, I know Lore has been listed as Depricated (which I really do hope won't be the case, or if it is, that Descriptions can inherit the Line-Wrap functionality), which if that is removed it'll potentially screw up lots of people's items. In my case that'd be a complete deal breaker for updating to 3.6, as I simply have too many items that use Lore and it's just not practical to try and change them **all** over to Description 😟
