### ISSUE TITLE
Better Offhand Support

### ISSUE THREAD

**Issue by Librazy** [NyaaCat/RPGitems-reloaded#269]

**Comment by Formula350** [comment]
Yes please! :) I was thinking of requesting stuff like...
- The main, obvious one being powers working while held in off-hand.
- The ability to activate off-hand items powers by holding Shift and right-clicking. *(I created a SkyHook that would've been nice for that)*
- The ability to assign items to ONLY work in Main or Off-hand
- In addition to that, the option to create "Two Hand" items that ***prevent*** the usage off the Off-hand slot. *(Look at OldCombatMechanics for a way to block the Off-hand slot)*
