### ISSUE TITLE
Vanilla enchant support

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#27]
Currently RPGitems can't be used with vanilla enchantments, player enchants an item will be rollback to the origin one.

For item distinguish purpose, RPGitems should at least support vanilla enchantments on command  but not user enchanting.

**Comment by Taiterio** [comment]
Adding something in so that a rebuild of an RPGItem does not destroy the enchantments while preventing users from enchanting RPGItems using the enchantment table

**Comment by Taiterio** [comment]
Implemented in commit 5d293476e71df7ee81c34660ce6a4ed016eecc05.
