### ISSUE TITLE
[SUGGESTION] Command removepower selector/power"changer" when multiple of same power

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGitems-reloaded#271]
When you have a power added more than once on a RPGItem and you want to change/remove the last power added, you have to remove ALL previously added powers to change that. A good example would be items that have multiple potionself powers. It's a pain to make changes to those items since you practially have to reapply all powers to those items.

It would be much better if you could have a line selector as with the command `description set`, or if you could add a command like `poweredit` or `powerchange` to make precise adjustments.

**Comment by miu-wen** [comment]
Power can be change it's parameter by `setter`  like:` /rpgitem [item] set command 1 cooldownTime 20`.

And get it's parameter by `getter`  like:`/rpgitem [item] getter commandhit 1 command` .

**Comment by Severdez** [comment]
It works like that? That's good to know. Thought that you could only set new parameters like burstCount/Interval or consumption like with `power projectile`. Thanks for the answer!

**Comment by Librazy** [comment]
Sorry for our poor and may misleading document, working on it!
