### ISSUE TITLE
[feature]耐久消耗支持 +0 与 -0 

### ISSUE THREAD

**Issue by miu-wen** [NyaaCat/RPGitems-reloaded#273]
如题，作用为在若消耗设置为 `+0` 则相对于durability为增加0，可被设定durabilitybound的max值过滤掉，反之`-0`可以被min值过滤掉。

作用于一般希望power不会产生消耗但是又在某个区间又不触发的场景

**Comment by Librazy** [comment]
use durabilitycondition
