### ISSUE TITLE
Custom Items cannot be used in Custom Crafting Recipes

### ISSUE THREAD

**Issue by Flugal** [NyaaCat/RPGitems-reloaded#277]
I'm using the last 2.5 version because none of the 2.6 snapshots would even remotely work: They wouldn't even load when the server started.
I can't use any of RPGItems items in crafting of more RPGitems. Can I get a fix or get this fixed?

**Comment by Librazy** [comment]
Custom recipe by plugin in 1.12/1.13+ is not recommend. Recipe support in RPGItems main plugin may be removed in future.
