### ISSUE TITLE
Stuck not clearing from players

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#282]
PowerStuck works well for mobs, but when players get hit and stucked, it keeps effective permanently.

**Comment by phoenixlzx** [comment]
Another issue:

Stuck in AOE mode does not calculate consumption.
Set `allowHit` to `false` and `allowAoe` to `true`
`costAoe` set to some value but not working.

**Comment by Librazy** [comment]
first fixed
cannot reproduce second
