### ISSUE TITLE
Don't work RPGitems recipe on 1.12.2

### ISSUE THREAD

**Issue by ungermum** [NyaaCat/RPGitems-reloaded#283]
I use last build of spigot.
When i use "rpgitem 1 recipe 1", nothing happens.
In the console I see errors
1. https://pastebin.com/wP24Wtyq
2. https://pastebin.com/LwQKW2jP
what the problem and how i can fix that?

**Comment by cyilin** [comment]
please use rpgitems 1.12-v3.6.295
