### ISSUE TITLE
Drop when you break some block

### ISSUE THREAD

**Issue by iLuros** [NyaaCat/RPGitems-reloaded#284]
Can you add command that can make some rpgitem dropped when a player break some block?
like /rpgitem [item] drop [blocktype] or something :D

**Comment by ReinWD** [comment]
Personally, I think it is a great idea, though some problems may occur.
First, this command means that you add a power to support your idea, but on current version, power cannot be triggered through mining with other tools. So, I think this feature can't be added immediately. But mining with a specific tool(have a "Vault Hunting" power) maybe can be added.
As a player of Nyaacat, I also suggest that the drop chance can be considered carefully. Any drop chance(even 0.1%) can cause serious item overproduce.
Hope this feature can be added soon.
@LurosKun

**Comment by Librazy** [comment]
Drop some items when you break some block is a great idea for adding fun to minecraft playing. However, crafting/dropping/selling RPGItems should decouple with RPGItems' main plugin.

**Comment by LurosKun** [comment]
Do you mean this will be add-on or what?
Sorry, I am not fluent in english

**Comment by ReinWD** [comment]
@iLuros working on it.
But not sure how long it takes.

**Comment by ReinWD** [comment]
http://reinwd.xyz/2018/01/04/whats-new-in-rpgitems-reloaded-featuring-power-treasure/
this function is basicly built up.
But it is achieved by power, which means that it can only be done by a specific RPGItem with this new power.
Later I will create a branch to finish global drop.

**Comment by Librazy** [comment]
won't fix for main plugin. Good idea for an extension.
