### ISSUE TITLE
Rules to trigger effect / power

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#29]
A new feature, to add rules such as player health, hunger, potion status, etc, to trigger on effects / powers on RPGitems.

This may bring more customizable and creative gaming experience.

**Comment by RecursiveG** [comment]
You want the actual effect vary depends on the player status?
I think it may be difficult to make a uniformed mechanism since it's power-dependent.
It may be better to alter the code of the power which you want to attach the feature to.

**Comment by phoenixlzx** [comment]
Not that complex I think, just enable the power when requirements are met if any rule is set to an item, only enable/disable, not vary.
