### ISSUE TITLE
Feature Request: Totem Ability

### ISSUE THREAD

**Issue by NomzHD** [NyaaCat/RPGitems-reloaded#290]
I'd like for items to be able to function similar to totems, but on a cooldown with a "/power totem" or something similar. Thats it, cheers!

**Comment by Librazy** [comment]
May PowerRescue helps？

**Comment by NomzHD** [comment]
Rescue is cool but the function where it teleports you away isn't what I want and the inPlace option does not work

**Comment by Librazy** [comment]
You need to turn off useBed too, useBed precede than inPlace.

**Comment by NomzHD** [comment]
So [/rpgitems whatever power rescue 1520 2 no inPlace] ?
