### ISSUE TITLE
Rpgitem names undetectable by Magicspells plugin (Will pay 25$ to fix asap)

### ISSUE THREAD

**Issue by getthegun** [NyaaCat/RPGitems-reloaded#293]
If I make a spell that has a modifier of either; wearing, holding, or hasitem to detect if the player is holding a specific named item, rpgitems do not get detected. 

If the modifier is: - hasitem 351:1|§c§lVampire__Badge required

A regular red dye modified to be called &c&lVampire Badge will work but an rpgitem called &c&lVampire Badge will not work.

I will pay $25 to whoever fixes this. The source code to magicspells is available here: https://github.com/TheComputerGeek2/MagicSpells

**Comment by cyilin** [comment]
put rpgitem into anvil, in output slot this item name like `000000177lWOOD_SWORD`, because vanilla does not allow `§` symbol, so this name is `§0§0§0§0§0§0§1§7§7§lWOOD_SWORD`
