### ISSUE TITLE
How can I make players give themselves items without permission?

### ISSUE THREAD

**Issue by durson54** [NyaaCat/RPGitems-reloaded#297]
So my server is RPG based and I have Quests there. But there's no option to make them choose their rewards so I decided to create ChestCommands menus where the Items (RPGItems) will be and they can choose. It worked but when I came on my player account it said I don't have permission. Basically I made menu and for example there's sword and when they click on it I added commad "rpgitem <name> give" but they don't have permission...So I'm wondering how to give them these items thru menus?

**Comment by Kristalyze** [comment]
I dont think your problem comes from rpgitem. It must come from your chest command, so check for permissions of this plugin and add them to your permission manager.

**Comment by durson54** [comment]
I think you didn't understand. The Menu makes them use command "rpgitem item give" so they don't have permission. What I meant is there a command that can give them thru this menu? Or I need to configure Chest Commands to give them permission or what? :D

**Comment by Kristalyze** [comment]
Oh I see. It's still a chest command issue. So try to make the console execute the command with 'console: command'

**Comment by durson54** [comment]
Not working.

**Comment by durson54** [comment]
Oh! :D I figured it out! :D It's working with 'op:command' :D I've been trying lot of different combinations and this works :D
