### ISSUE TITLE
Power stuck teleport denial not working?

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGitems-reloaded#302]
In your newest update log on spigot (https://www.spigotmc.org/resources/rpgitems.17549/updates), you wrote that the power stuck would block teleport. For me it only stops movement but not teleportation. Players can still teleport away with items, that have the power teleport.

**Comment by Midnight9746** [comment]
Pretty sure it blocks teleporting when you use it on another player.

**Comment by Severdez** [comment]
After pretty much updating everything, all other ugs were fixed. Will test this again later.
