### ISSUE TITLE
I can't use /rpgitem [item] customItemModel....

### ISSUE THREAD

**Issue by OngMong** [NyaaCat/RPGItems-reloaded#314]
I am using the version for 1.9 and the Server version is also 1.9.
I can't use '/rpgitem [item] customItemModel'.
when I type it, It makes loooong messages.
![2018-06-23_19 08 02](https://user-images.githubusercontent.com/38278609/41808461-d2e58e94-7718-11e8-9467-0f58f9545399.png)

**Comment by Librazy** [comment]
Custom item model is only support by 1.11 and onwards. 
https://github.com/NyaaCat/RPGitems-reloaded/commit/79b135bc130ea7e4328da11d76e23ad8aeebced4

**Comment by OngMong** [comment]
@Librazy hmm.. but it worked without that command!
I just needed to use durability texture.

**Comment by OngMong** [comment]
ah, do you know how to hide it?
![2018-06-23_19 44 27](https://user-images.githubusercontent.com/38278609/41808796-0313afc4-771e-11e8-9382-89805eea00b9.png)

**Comment by Librazy** [comment]
see #157 for ItemFlags
