### ISSUE TITLE
Oh...... It doesn't show 3D model (durability unbreakable texture) when I restart the server.

### ISSUE THREAD

**Issue by OngMong** [NyaaCat/RPGItems-reloaded#315]
It shows right texture when I create the item, but after a restart or stop & start,
It suddenly doesn't show the custom texture or model, there is just a vanila one.
I am using it for 1.9... and I know It's not maintained, but....
I need a help.. If there is nothing to solve this problem,
Could you recommend me a plugin to create a item , edit and make recipe??

**Comment by Librazy** [comment]
Custom item model is not supported in 1.9 version. See #197 for 1.11+ support
