### ISSUE TITLE
Items in cooldown will still be consumed

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#32]
When using an item within cooldown timecount, the item will be consumed without effect.

**Comment by Taiterio** [comment]
The consume power would have to be rewritten in a way so that it does not listen to a rightclick event if another power is on the item. Maybe we should add a secondary event onPowerUse that will trigger it and only use rightClick when the item has no other powers?

**Comment by Librazy** [comment]
Durability are preferred for most case.
