### ISSUE TITLE
RPGITEM ITEM DAMAGES IN COLOUR AND POTION EFFECTS IN COLOUR...

### ISSUE THREAD

**Issue by xZpark** [NyaaCat/RPGitems-reloaded#322]
![image](https://user-images.githubusercontent.com/41338573/42827389-8531d708-89e6-11e8-975e-307f7cdac8af.png)
 
Hello.
I need to change the Item displays.From the down image to UP image.

![image](https://user-images.githubusercontent.com/41338573/42827601-1b991404-89e7-11e8-9957-1965d46f01ac.png)

**Comment by Librazy** [comment]
One way to achieve this is to `togglePowerLore` `toggleArmorLore` `itemflag HIDE_ATTRIBUTES` and then you can customize all the lores.
