### ISSUE TITLE
Armour not working with CrackShot

### ISSUE THREAD

**Issue by Vyrgax** [NyaaCat/RPGitems-reloaded#328]
I recently noticed < /rpgitem x armour > doesn't reduce the damage of CrackShot items. It seems to work fine with swords and bows, but it won't reduce the damage of guns. Would be great if a fix would be considered for this :)

Sincerely,
Vyrgax

**Comment by Librazy** [comment]
won't fix for main plugin. there are enough API to make an extension. stay turned
