### ISSUE TITLE
请求发射羊毛功能扩展

### ISSUE THREAD

**Issue by 17windy** [NyaaCat/RPGitems-reloaded#33]
目前已经可以发射羊毛或者火
请求增加下可以发射凋灵骷髅（凋零发射的那个）、雪球、烈焰人飞弹的扩展功能。
谢谢！

**Comment by RecursiveG** [comment]
Translate: Request to extend the function of PowerRainbow
To make it able to fire wither skull, snowball and fireball.

**Comment by Taiterio** [comment]
Wouldn't it be better to create a new power for each projectile like it is done with the arrow power? The Rainbow power is designed to shoot blocks instead of standard projectiles.
