### ISSUE TITLE
I have a problem.....

### ISSUE THREAD

**Issue by Grazhangjunde** [NyaaCat/RPGitems-reloaded#335]
Sorry , please help me solve this problem.
In server , I can use ./rpgitem but I can't create a new project.
In game , when creating a new project , the plugin does't send any message in the game.
But in the console it show some error message .

![qq 20180906002102](https://user-images.githubusercontent.com/17041926/45107005-cbe17400-b16a-11e8-816e-77743a559dbc.png)

**Comment by cyilin** [comment]
this error may be caused by a forge mod
