### ISSUE TITLE
Problem with crafting recipes

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGitems-reloaded#340]
Since updating to 1.11-v3.5.448 I am experiencing weird problems with crafting recipes. Old recipes, that used to work are no longer functioning. Also weird is that some other items, that are working with the same concept, seem to work fine.

As you can see here:
https://puu.sh/BN9hM/b00e2c6b38.png
These two crafting recipes work fine. However with the next set of items, that work with the same concept don't:
https://puu.sh/BN9mi/dae2036d11.png

What also seems weird to me, is that another item, using the same material as the one above works perfectly fine:
https://puu.sh/BN9eK/f523c1c4ee.png

All items used in these crafting recipes are RPGItems.

**Comment by Severdez** [comment]
Removing and recreating the item doesn't fix the problem, but changing the recipe to something else strangely does.

https://puu.sh/BN9uY/86639e2102.png

There are no other items sharing the same recipe, though.

**Comment by Librazy** [comment]
Custom recipe by plugin in 1.12/1.13+ is not recommend. Recipe support in RPGItems main plugin may be removed in future.
