### ISSUE TITLE
Request： Keep Lore data on RPGITEM

### ISSUE THREAD

**Issue by MERRYACS** [NyaaCat/RPGitems-reloaded#343]
the old RPGITEM can allow you to toggle the lore keep and enchant keep, i tested in my 1.12 server with version v3.5 it keep the enchant, but not lores data.
i want to use other lores plugin to add lore onto rpgitem's item

**Comment by Librazy** [comment]
Use power lorefilter to add regex patterns of lores which you wants to keep.

**Comment by GailKabala** [comment]
@Librazy  do you have examples? I haven't succeeded.
