### ISSUE TITLE
WorldGuard/WorldEdit 6.x Compatibility

### ISSUE THREAD

**Issue by MarkElf** [NyaaCat/RPGItems-reloaded#344]
I get this error when someone joins. I'm using asyncworldedit premium - as I see world edit I thought it's worth mentioning.
https://pastebin.com/M7uP4unU

**Comment by Librazy** [comment]
As a workaround you can use `/rpgitem worldguard` to disable worldguard integration.

**Comment by MarkElf** [comment]
I see. Thank you for the quick response.
