### ISSUE TITLE
请求新功能 AT立场

### ISSUE THREAD

**Issue by 17windy** [NyaaCat/RPGitems-reloaded#35]
右键使用可以以自身为圆心设立 材质为a 以x半径y高度存在z秒时间 的圆柱形防护墙 放置时候会自动检测周围环境 防止覆盖现有方块或者命名牌一类的物品

**Comment by Taiterio** [comment]
As far as I have understood you want a power that creates a protective barrier with configurable x, y and z, that keeps any blocks intact that it is configured to. This can be achieved very nicely using the barrier blocks, although that would make the plugin depend on 1.8, so a fallback must be added.

**Comment by RecursiveG** [comment]
@Taiterio Yes, that's what he's talking about. And maybe we can use "block 36" as the fallback?
