### ISSUE TITLE
Deflect power not working

### ISSUE THREAD

**Issue by Vyrgax** [NyaaCat/RPGItems-reloaded#350]
The deflect power does not function correctly.

## Describe the Bug:
Any RPGitem with the deflect power doesn't work: On right-click the item disappears.

1. Install both latest RPGItems, NyaaCore and Langutils
2. Create an item with the deflect power
3. Try deflecting (Right click). The item disappears on right click.

### Expected Behavior
Supposed not to disappear; it should deflect arrow and other projectiles (mostly).

### Stacktrace or log
No error logs.

## Environment

- Java version: 8
- Server software version: 1.13.2
- RPGItems version :rpgitem-reloaded-3.6.552-mc1.13.2.jar

The deflect power worked in version 3.6.252
Though, it only blocked the projectile, it didn't deflect them back.

**Comment by Librazy** [comment]
maybe not related to deflect but a default durability le 0. Supposed to be fixed by d58174a

**Comment by Librazy** [comment]
Sorry for the long delay. Fixed in https://github.com/NyaaCat/RPGItems-reloaded/releases/tag/v3.6.559-mc1.13.2

**Comment by Librazy** [comment]
Fixed in https://github.com/NyaaCat/RPGItems-reloaded/releases/tag/v3.6.560-mc1.13.2 . Release 559 is broken.
