### ISSUE TITLE
Deflect power working; though, not fully

### ISSUE THREAD

**Issue by Vyrgax** [NyaaCat/RPGItems-reloaded#351]
# Bug Report
Deflect power is working, as in, it blocks the incoming projectiles: Though, it doesn't deflect back.
## Describe the Bug
When trying to deflect incoming projectiles, and hold right click, the projectile is blocked, but it won't fire back.

## To Reproduce

1. Create a RPGItem with the deflect power.
2. Summon a default skeleton.
3. Enter gamemode survival with the RPGItem
4. Enter combat with the skeleton and try deflecting the arrows.
If the arrow hits you and you're deflecting, you'll hear the sound, and you won't receive damage.
Though, it doesn't fire back.

### Expected Behavior

When deflecting projectiles the projectiles should be fired back/bounced back and inflict damage.

### Stacktrace or log

No logs.

## Environment

- Java version: 8
- Server software version: 1.13.2
- RPGItems version: v3.6.560-mc1.13.2

## Additional Context

Thanks for the fast fix for the previous bug report!

**Comment by Librazy** [comment]
Not reproducible but noticed a thing may help.
https://github.com/NyaaCat/RPGItems-reloaded/releases/tag/v3.6.563-mc1.13.2

**Comment by Librazy** [comment]
Current implementation of deflect is cancelling the damage event and set the shooter of projectile to player, wait the projectile to drop naturally **some** tick, then set the direction and velocity based on player's facing. Maybe the delay is too long.
