### ISSUE TITLE
I have a problem whit all commands 

### ISSUE THREAD

**Issue by Seba041** [NyaaCat/RPGItems-reloaded#352]
# Bug Report

## Describe the Bug

I cant user any commands of the plugin

## To Reproduce

1. Put any rpgitems command in the chat
2. ...
3. ...

### Screenshots

![fwefwefweffw](https://user-images.githubusercontent.com/47116096/51851289-584f2780-2302-11e9-8fb5-425ee265d49f.png)
![fwfw](https://user-images.githubusercontent.com/47116096/51851321-6a30ca80-2302-11e9-9c50-45a28e21375a.png)

### Stacktrace or log

If applicable, add stacktrace or log during the issue.

## Environment

- Java version: [ the latest ]
- Server software version: [ 1.13 ]
- RPGItems version: [ 3.6.569 ]

**Comment by cyilin** [comment]
rpgitems 3.6.569 only support spigot 1.13.2.
