### ISSUE TITLE
 HIDE_ATTRIBUTES itemflag not working with power attributemodifier

### ISSUE THREAD

**Issue by Acappella-nano** [NyaaCat/RPGItems-reloaded#355]
When I add the power `attributemodifier` to my item, which has the item flag `HIDE_ATTRIBUTES` on it, it comes out that I can still see the attributes on the item. This item flag works fine without `attributemodifier` power.

I tried other item flags like `HIDE_ENCHANTS` and `HIDE_UNBREAKABLE`, and they are alright. 

Here's a screenshot of the item.

![image](https://user-images.githubusercontent.com/43006287/53810019-ffbe1a80-3f90-11e9-8070-28ed9c6bb390.png)

I'm using peper spigot version 551 and the latest version of RPGItem and NyaaCore.

**Comment by Librazy** [comment]
It is a feature (
