### ISSUE TITLE
Block Type RPGitems are placeable

### ISSUE THREAD

**Issue by Heyowe** [NyaaCat/RPGItems-reloaded#359]
# Bug Report

## Describe the Bug

Block type items like dirt, chests, heads etc are placeable.

## To Reproduce

1. ...hold block type rpgitem
2. ...place
3. ...becomes an ordinary item after being placed

### Expected Behavior

happens everytime i place a block type rpg item

### Screenshots

N/A

### Stacktrace or log

N/A

## Environment

- Java version: [ java -version ]
- Server software version: 1.13.2
- RPGItems version: 3.6.593

**Comment by Librazy** [comment]
not reproducible in recent versions, and we should have already fixed this problem by https://github.com/NyaaCat/RPGItems-reloaded/blob/b5d3ea9965562fb1892b5481f254e30a442ae74d/src/main/java/think/rpgitems/Events.java#L407
