### ISSUE TITLE
Colouring Leather Armour doesn't work.

### ISSUE THREAD

**Issue by Vyrgax** [NyaaCat/RPGItems-reloaded#363]
# Bug Report
The item_colour mechanic doesn't work with leather armour, meaning you can't dye these armour pieces.

## Describe the Bug
`/rpgitem myhelmet item LEATHER_HELMET hex [hex color code]`
with a hex color code (take #1d1d21 as example, black), it doesn't colour. 

## To Reproduce

1. /rpgitem myhelmet item LEATHER_HELMET hex #1d1d21
2. /rpgitem reload to make sure
3. /rpgitem myhelmet give; it's not dyed.

### Expected Behavior
After executing the command given above the armour should be dyed.

## Environment

- Java version: java 8 - openj9
- Server software version: 1.13.2 spigot
- RPGItems version: 3.7.596-mc1.13.2

**Comment by Librazy** [comment]
Should work now
