### ISSUE TITLE
[Feature Request] Mending & EnchantmentCondition

### ISSUE THREAD

**Issue by Acappellia** [NyaaCat/RPGItems-reloaded#367]
# Feature Request

## Describe the Solution You'd Like

Add a power which is similar to Minecraft mending. When you pick up an xp orb, the xp won't be added to xp bar, but restores some durability instead.

It could have the following parameters:

- `repairFactor` Durability restored per point of xp. Can be set to 2 by default.
- `enchantmentBased` If set to true, mending only takes effect when the item has `MENDING` enchantment on it.

Additionally, one xp orb should repair ONE item only. If the durability is full, the xp can be added to player's xp bar.

**Comment by Clexus** [comment]
not quite possible

**Comment by Clexus** [comment]
Finished
