### ISSUE TITLE
请求新功能 羊毛/粘土颜色修改

### ISSUE THREAD

**Issue by 17windy** [NyaaCat/RPGitems-reloaded#37]
右键使用 可以针对任何颜色羊毛/粘土方块 使其变成目前设置的颜色

**Comment by Taiterio** [comment]
Should it also applay for glass in newer minecraft versions?

**Comment by Taiterio** [comment]
This power is currently bound to blocks, the block represents the color it will set on a colorable block. This is used to make WorldGuard build permission checks unnecessary, as WG can simply cancel the event to stop the power from applying the effect in areas where this is unwanted.
