### ISSUE TITLE
请求新功能 南瓜怪人

### ISSUE THREAD

**Issue by 17windy** [NyaaCat/RPGitems-reloaded#38]
左键攻击x几率触发 让目标（僵尸+骷髅）的头部装备变成南瓜 同时附加LVy的凋零效果z秒

**Comment by Taiterio** [comment]
The idea is to give zombies/skeletons pumpkin heads when triggered by combat that kill after a set delay as far as I could gather.

**Comment by RecursiveG** [comment]
Since the wither effect can be achieved with PowerPotionHit. Only the pumpkin head effect was implemented in PowerPumpkin.
