### ISSUE TITLE
Add trigger SNEAK to power potiontick

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGItems-reloaded#380]
# Feature Request

## Is Your Feature Request Related to a Problem? Please Describe.

I want to create an item, that makes a player invisible only while sneaking. Potionself with the trigger SNEAK is no solution, as it keeps the player invisible, even after he STOPS sneaking (or he loses invisibility while sneaking). Potiontick currently only accepts the trigger TICK.

## Describe the Solution You'd Like

Add the trigger SNEAK to the power potiontick. This allows items to have a potioneffect ONLY while sneaking. Thanks for any answer in advance.

**Comment by Librazy** [comment]
we added trigger SNEAKING recently and I'll add SNEAKING to potiontick
