### ISSUE TITLE
Add a clear option to [POTIONTICK], just like [POTIONSELF] does

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGItems-reloaded#381]
# Feature Request

## Is Your Feature Request Related to a Problem? Please Describe.

The power potiontick has a `clear` option, which allows for potioneffects to be removed instead of applied. Having the same option for power `potionself` would allow for the creation of items, that heal you of some potioneffects. (Same thing was possible before by having the duration 1 tick or so, but that would simplify it.)

## Describe the Solution You'd Like

Add the option `clear` to the power `potionself` with the options true or false

**Comment by Librazy** [comment]
done
