### ISSUE TITLE
Infinite durability is not working on items with vanilla durability

### ISSUE THREAD

**Issue by Severdez** [NyaaCat/RPGItems-reloaded#386]
# Bug Report

## Describe the Bug

If you create a RPGItem and set the `ITEM` to something that has durability in vanilla minecraft, then setting it to `durability infinite` does not make it indestructible. Instead it keeps its vanilla durability.

## To Reproduce

1. Create a RPGItem and set the `ITEM` to something, that has durability in vanilla minecraft (Swords, bow, tools or armor)
2. Set the `durability` of the item to `infninite`
3. Do something that damages the items durability and you should see that it loses durability until it breaks (Reaches 0 durability)

### Expected Behavior

The RPGItem should have infinite durability and so should not lose any of it.

### Screenshots

Not a screenshot, but uploaded it to YouTube:
https://youtu.be/voByfdBVz8c

## Environment

- Java version: 1.8.0_191
- Server software version: spigot 1.13.2
- RPGItems version: 3.7.671

**Comment by Librazy** [comment]
The vanilla durability is maintained by vanilla and we only update them when updating the item. And we should have been preventing the item from breaking (https://github.com/NyaaCat/RPGItems-reloaded/blob/5455b10603deb2377a77cc17a0564b13604f06dc/src/main/java/think/rpgitems/Events.java#L754) I'll investigate whether it is still working.
