### ISSUE TITLE
Can't add spaces when changing display name or description

### ISSUE THREAD

**Issue by QuazArxx** [NyaaCat/RPGItems-reloaded#387]
For some reason when I try to add a display name to my item or a description, it only takes the first word used.

/rpgitem god_sword display &4God Sword

This command only gives me a sword named "God"

/rpgitem god_sword description &1A sword passed down by the gods' themselves

This command only displays the description of the sword as "A"

**Comment by phoenixlzx** [comment]
Use backquote.

https://github.com/NyaaCat/RPGItems-reloaded/wiki/Item-Customization#rpgitem-item-display--rpgitem-item-value
