### ISSUE TITLE
请求新功能 以撒献祭

### ISSUE THREAD

**Issue by 17windy** [NyaaCat/RPGitems-reloaded#39]
左键x几率触发 角色立刻死亡 死亡同时在原地召唤（mob类型 - 可以设定怪物nbt）怪物y只。

**Comment by RecursiveG** [comment]
The example in the comment is wrong. The correct one should be
/rpgitem somesword power deathcommand 100 3 `summon Zombie ${x} ${y} ${z} {CustomName:BODY,CustomNameVisible:1}` `spawn three zombies`
There's no slash before `summon`
