### ISSUE TITLE
Is there an ETA on 1.14 support?

### ISSUE THREAD

**Issue by willywizard** [NyaaCat/RPGItems-reloaded#392]
I am going to assume that support for this plugin will continue, so is there an ETA on 1.14 support? With the new ability to make unlimited textures for a single item RPG servers, and just servers in general with Custom items should be on the rise again and fairly soon at that.

So is there an ETA? Or will it still be a long while?

**Comment by phoenixlzx** [comment]
We are working on it. Please do not push.
