### ISSUE TITLE
Gunfu 和 beam 的新参数

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGItems-reloaded#393]
- [x] gunfu 的追踪延迟
- [x] beam 伤害判定使用离子半径(粒子碰撞箱)和实体碰撞箱
- [x] beam 的 `homing` `homingRange` 和 `homingAngle` 参数
- [x] beam 的 `cone` 和 `coneRange` 参数
- [x] beam 的 `burstCount` 和 `burstInterval` 参数
- [x] beam 的 `bounce` 和 `hitSelf` 参数，该参数启用时 `ignoreWall` 参数不生效

以上参数都有默认值且默认即不生效。

**Comment by ReinWD** [comment]
done
