### ISSUE TITLE
Dynamic trigger

### ISSUE THREAD

**Issue by Librazy** [NyaaCat/RPGItems-reloaded#409]
# Feature Request

## Is Your Feature Request Related to a Problem? Please Describe.

N/A

## Describe the Solution You'd Like

You can define a trigger in a per-item basis, such as "Hit enemy with a minimum damage of 100" or "Sprint for X-second" or even "W-W-S-S-A-D-A-D sequence".

## Describe Alternatives You've Considered

1. More trigger

Too restricted and no customization.

2. Global trigger definition

Can't share with item yml.

## Additional Context

N/A

**Comment by Clexus** [comment]
some are implemented now
some are impossible
