### ISSUE TITLE
RPGITEM error spam every day

### ISSUE THREAD

**Issue by xxBoWiExx** [NyaaCat/RPGItems-reloaded#410]
Error with RPG Items

My Console has an spam error every day, i dont know realy why this happen, recently i updated from 1.8.
`ion
java.lang.NullPointerException: null
[23:08:56 WARN]: [RPGItems] Task #24611470 for RPGItems v3.7.697-mc1.13.2 generated an exception
java.lang.NullPointerException: null
[23:08:56 WARN]: [RPGItems] Task #2570 for RPGItems v3.7.697-mc1.13.2 generated an exception
java.lang.NullPointerException: null
[23:08:56 WARN]: [RPGItems] Task #2570 for RPGItems v3.7.697-mc1.13.2 generated an exception
java.lang.NullPointerException: null
[23:08:56 WARN]: [RPGItems] Task #2570 for RPGItems v3.7.697-mc1.13.2 generated an exception
java.lang.NullPointerException: null
[23:08:56 WARN]: [RPGItems] Task #2570 for RPGItems v3.7.697-mc1.13.2 generated an exception
java.lang.NullPointerException: null
[23:08:57 WARN]: [RPGItems] Tas`

**Comment by ReinWD** [comment]
May you give us a full log file or the first occurance of this exception?  These lines don't have stack trace so we don't really know where it happens.

**Comment by xxBoWiExx** [comment]
Hi, i have been watching that probably the essentials broke the rpgs, i have some rpgs in the essentials kits, but randomly some rpgs broke (lose all the efects) and others doesnt, i recently update all my  rpgs (aprox 562 rpgs), i use the latest version of essentials X and  KitAdder in order to put the rpgs in kits. I use via version and protocol suport and old combat mechanics

**Comment by xxBoWiExx** [comment]
i recently update from 1.8 to 1.13*

**Comment by xxBoWiExx** [comment]
this is my startup

https://pastebin.com/5UkNb3Uz

**Comment by xxBoWiExx** [comment]
When the server  is in whitelist and my admins and I are testing, every thing is ok, but when enter all the people  all the spam starts and lose efects in every change of world,

**Comment by xxBoWiExx** [comment]
I think that when a person is using a broken rpg all the rpgs lose efects, when nobody is using rpgs broken the rpgs are ok, but now the problem.

**Comment by xxBoWiExx** [comment]
I have downgrade to the 1.8 version. Close the ticket.
