### ISSUE TITLE
后台报错+耐久设置无效

### ISSUE THREAD

**Issue by KoitoTouko** [NyaaCat/RPGItems-reloaded#412]
# 问题反馈

加载没有问题，输入指令时报错，提示
>.... [10:32:24 WARN]: [RPGItems] Missing language key: manual.no_usage
>.... [10:32:24 WARN]: [RPGItems] Missing language key: manual.no_description
而且设置耐久无效，无论怎么设置都是无限耐久（看了耐久条一直不变）

## 环境

- Java 版本：java8
- 服务端版本：1.14.4
- RPGItems 版本：3.8.14

**Comment by ReinWD** [comment]
应该是指令格式错误。
试试更新[最新版本](https://ci.nyaacat.com/job/RPGItems-reloaded/)（1.15.1）
最新版本的命令补全应该可以解决这种问题

**Comment by ReinWD** [comment]
最近的实验性功能可能会有点多，建议升级前备份。
