### ISSUE TITLE
I tryed to do that in 1.15 and 1.15.1 but it give errors.

### ISSUE THREAD

**Issue by Akalstik** [NyaaCat/RPGItems-reloaded#413]
# Bug Report

## Describe the Bug
WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

[WARNING] [RPGItems] Missing language key: manual.no_description

[WARNING] [RPGItems] Missing language key: manual.no_usage

## To Reproduce

1. ...
2. ...
3. ...

### Screenshots
![image](https://user-images.githubusercontent.com/59395298/71625658-a2ffb080-2bf1-11ea-9ec3-c5ee433db447.png)

![image](https://user-images.githubusercontent.com/59395298/71625662-a6933780-2bf1-11ea-8fa8-dd29a2dd143b.png)

![image](https://user-images.githubusercontent.com/59395298/71625645-9b400c00-2bf1-11ea-9e11-d4257555e606.png)

![image](https://user-images.githubusercontent.com/59395298/71625692-d9d5c680-2bf1-11ea-9855-1e7b86b74e72.png)

### Stacktrace or log

If applicable, add stacktrace or log during the issue.

## Environment

- Java version: [ java -version ]
- Server software version: [ /version 1.15/1.15.1 ]
- RPGItems version: [ /rpgitem version 3.8.1 ]

## Additional Context
Help please.

**Comment by Ilmatarnyymi** [comment]
same happens on 1.15.2

**Comment by Eustiya** [comment]
so do i

**Comment by ReinWD** [comment]
It suggested that the command isn't correct.
And no help message provided.
Try to use [a new build](https://ci.nyaacat.com/job/RPGItems-reloaded/) and follow the auto completion.

**Comment by ReinWD** [comment]
Back up item cfg before upgrading, plz.

**Comment by Eustiya** [comment]
It can be used only to help the language break

**Comment by GailKabala** [comment]
so do i
