### ISSUE TITLE
CustomModelData texture pack override compatibility

### ISSUE THREAD

**Issue by Ilmatarnyymi** [NyaaCat/RPGItems-reloaded#419]
CustomModelData

I dont use durability for custom models anymore so i would love to see the new CustomModelData used in this great plugin

I suggest you add a way to add the CustomModelData NBT into rpgitems.

**Comment by ReinWD** [comment]
good idea.
added to wishlist.

**Comment by GailKabala** [comment]
+1

**Comment by phoenixlzx** [comment]
You can try this version if you are using 1.15.2

https://ci.nyaacat.com/job/RPGItems-reloaded/job/1.15/74/artifact/build/libs/RPGItems-mc1.15-3.8-74-release.jar

**Comment by ReinWD** [comment]
Try also [ROTA](https://github.com/NyaaCat/ROTA) plugin.
ROTA (Resource pack Over The Air) plugin is our Resource pack distribution solution.

Our server is already been using CustomModelData for a week. And it's GREAT!
