### ISSUE TITLE
DamageType and ArmourExpression seems no-use and not work.

### ISSUE THREAD

**Issue by engineer1109** [NyaaCat/RPGItems-reloaded#422]
# Bug Report

## Describe the Bug

1.   /rpgitem armorExpression test magic

The console got
```
 [RPGItems] Missing language key: message.error.invalid_expression
```
2. I view the source 
```
public double takeDamage(Player p, double originDamage, ItemStack stack, Entity damager)
```
I found damageType and ArmourExpression is just get() and set().
They don't work in the combat event.

## To Reproduce

1. /rpgitem armorExpression test magic

## Environment

- Java version: 241
- Server software version: paper 1.15.2
- RPGItems version: 3.8-76

## Additional Context

中文：
1.   /rpgitem armorExpression test magic
这个命令没有作用，tab补全的，string判断也不给过。
2. damageType 和 ArmourExpression 没有作用，或意义不明，是未完成吗？

**Comment by ReinWD** [comment]
这两项功能都是定制化解决某些问题的方案。很高兴你可以主动去尝试了解它们。

damageType用于 damageTypeCondition.
可以用作特定类型伤害的加伤判定。
可以尝试使用hit/hit_global触发的evaldamage power做指定类型的伤害加成哦

armorExperssion通过EvalEx库进行实时减伤计算（该结算优先于hit trigger触发），适合用于护甲道具，可以做到先减伤后结算。
支持的变量名可以在[这里](https://github.com/NyaaCat/RPGItems-reloaded/blob/035639ed2d77e122095effe5a6b3a92635a09b5b/src/main/java/think/rpgitems/power/Utils.java#L864) 查看

**Comment by engineer1109** [comment]
@ReinWD Thanks for replying. 谢谢回复

**Comment by engineer1109** [comment]
/rpgitem armorExpression testarmour finalDamage*2
It works.
受伤害增加100% 蛤
