### ISSUE TITLE
How can I use AndConditions , OrConditions, XorConditions

### ISSUE THREAD

**Issue by engineer1109** [NyaaCat/RPGItems-reloaded#423]
# 问题反馈

## 描述你遇到的问题

我已经知道简单的条件如何去编写。
但是，AndConditions , OrConditions, XorConditions 这些是怎么写的呢？

我尝试在AndConditions里
填写Conditions: Test1,Test2
发现只对Test1 有反应。。。

源码我也没怎么看明白，这泛型很迷惑
```
public PowerResult<Map.Entry<Condition<?>, PowerResult<?>>> check(Player player, ItemStack stack, Map<PropertyHolder, PowerResult<?>> context) 
```

**Comment by ReinWD** [comment]
以XorCondition为例
conditions里面放上需要进行逻辑运算的condition id
'conditions:cond1,cond2'
'id:cond3'
这样cond3的结果就等于cond1和cond2的异或结果了
（如果不对我回去问一下经常用这功能的策划））
