### ISSUE TITLE
How do I use multiple argument commands? (with powers) 

### ISSUE THREAD

**Issue by RedPxnda** [NyaaCat/RPGItems-reloaded#425]
How do I make a command power with multiple arguments but it doesn't work. I've tried doing command:\minecraft:give {player} stone``. I've also tried quotes: "; and single quotes: '.
it prompts me with the help text when I press enter.

**Comment by engineer1109** [comment]
manually change the yml

**Comment by RedPxnda** [comment]
oh ok

**Comment by Clexus** [comment]
/rpgitem power add item command command:`command with args`
