### ISSUE TITLE
/rpgitem give <item>. Doesn't work

### ISSUE THREAD

**Issue by TacoLatte** [NyaaCat/RPGItems-reloaded#428]
# Bug Report

/rpgitem give <item> causes the feedback "Internal server error. Unable to run command"

## Describe the Bug

I made an item and when I tried to give it to myself this happened. I thought I might have done something wrong so I followed the tutorial on the spigot page. It still didn't work. Is this a bug or do I have the brain capacity of a two-year-old?

## To Reproduce

Steps to reproduce the behaviour:

1. Follow guide on spigot page or make own item
2. Do /rpgitem give <item name>
3. Recieve the error message and get mad.

### Expected Behavior

I expected to receive the item.

### Screenshots

![image](https://user-images.githubusercontent.com/37388026/78740139-f33e8b00-7923-11ea-8eff-fb99386f302b.png)

### Stacktrace or log

[](url)https://pastebin.com/u6KqB12P

## Environment

- Java version: [ Version 8 Update 241. Build 1.8.0_241-b07]
- Server software version: [ Paper version 1.15.2-R0.1-SNAPSHOT]
- RPGItems version: [ /rpgitem 3,8-76]

## Additional Context

I am using this on minehut. Which could be the reason why the game is dying

**Comment by Tlahtoacoatl** [comment]
It seems that Minehut is the issue here with the plugin. I tried using another server and it worked fine.
 :(
