### ISSUE TITLE
[Suggestion] Filter the Citizen NPC while rpgitems:attract

### ISSUE THREAD

**Issue by engineer1109** [NyaaCat/RPGItems-reloaded#432]
# 功能请求

## 你的功能请求是否和一个问题有关？如果是，请在此描述

rpgitems:attract的功能 能不能过滤掉 citizen的NPC？

## 你的想法

我觉得这比较难，需要hook别的插件。

**Comment by engineer1109** [comment]
glove也是这个问题，selector有没有办法

**Comment by Clexus** [comment]
满足`!entity.hasMetadata("NPC")`即可，每个NPC都会包含一个叫做NPC的Metadata，甚至不需要钩citizens
