### ISSUE TITLE
Issue with the give command

### ISSUE THREAD

**Issue by althailed** [NyaaCat/RPGItems-reloaded#435]
I can't do /rpgitem give {name}, or anything like that. It just says internal server error. 
Also, just a FYI, this is being run on a minehut server, which is probably causing the problem.

**Comment by ReinWD** [comment]
don't know if there's any error report
if present, plz paste it on a pastebin and post the link here, and we can locate the problem.

**Comment by RandyGamers** [comment]
I had same problem with membotz 
[ERROR] Error occurred while enabling NyaaCore v7.2.367 (Is it up to date?) 
https://pastebin.com/Gq7z6081

**Comment by RandyGamers** [comment]
Can anyone help me ???
