### ISSUE TITLE
Condition Format

### ISSUE THREAD

**Issue by TheFast444** [NyaaCat/RPGItems-reloaded#436]
I get no idea from the official web, i try to type but that didn't work at all or maybe my command format was wrong, but there is too less info for user, you are do it without pay any serious . i really cant understand what the function condition and some function, if can please update the official web and give example clearly for the function , thank you.

/rpgitem condition add test1 andcondition conditions:test1,test2 id:test
/rpgitem condition add test2 andcondition conditions:test1,test2 id:test
/rpgitem power add test1 potiontick amplifier:4 effect:INCREASE_DAMAGE conditions:test
/rpgitem power add test2 potiontick amplifier:4 effect:INCREASE_DAMAGE conditions:test

Is any wrong there?  i wanna do a weapon put on offhand and mainhand and get the buff

真的是看不懂官網啦，希望官網快快更新，condition什麼的都弄不出來，明明只想弄一個套裝

**Comment by phoenixlzx** [comment]
新的文档在这里 https://nyaacat.github.io/RPGItems-wiki/#/zh-cn/

**Comment by TheFast444** [comment]
這只是中文版吧 .-.

**Comment by engineer1109** [comment]
andcondition is buggy.
You can
/rpgitem power add test1 potiontick amplifier:4 effect:INCREASE_DAMAGE conditions:test1,test2
