### ISSUE TITLE
How to update from 1.12.2 to 1.15.2?

### ISSUE THREAD

**Issue by Espinete87** [NyaaCat/RPGItems-reloaded#438]
Hello guys, im having problems with update, im coming from mc 1.12.2 with rpgitem-reloaded-mc1.11-v3.5.319 and i tried to update to 1.15.2  with RPGItems-mc1.15-3.8-103-release.jar

Im not sure if this is the way, but i did what is written in "Update From v3.5" in https://github.com/NyaaCat/RPGItems-reloaded/wiki/RPGItems-3.6-for-1.13.2-Upgrade-Guide JUST THE FIRST STEP, and is not working.
Do i need to update step by step? or is correct just to leave the old rpgitems folder, and start the server 1.15.2? ( of course adding the last versions of Vault
NyaaCore
LangUtils
RPGItems

One of the problems i see is, /rpgitem create mysword and other items doesnt works anymore ( when i have tried the plugin from zero, it was working everything) 
Also what i see now is the items, ext, and backup folders are empty >.<

The log is here: https://file.io/XnpWHFjN   (could not load to pastebin)
Thanks

**Comment by Espinete87** [comment]
up

**Comment by Espinete87** [comment]
up

**Comment by ReinWD** [comment]
try upgrade your items using version 3.6 in 1.13.
v3.8 is a refactor version and upgrading may not included.
items in 1.13.2 may work fine in 1.15.
