### ISSUE TITLE
More attribute

### ISSUE THREAD

**Issue by CareLessNo** [NyaaCat/RPGitems-reloaded#44]
This article is made by mechanical translation
Equipment set attribute
If you get the full set of equipment
You can get more attribute ,like damage,health ...
Title,If you have a title with attribute,you wear it you will get the attribute
The next one ,A medal,the medal can get attribute if you take it into your backpack
Can set the role of type, check the type,and then through the type type of different to define the different ways to obtain properties
The last one are bind equipment with the particle effects
中文 
装备套装属性
 凑齐一套装备可以获得附加的属性
 称号，如果可以加的话，称号属性，带上某个称号可以获得属性
 勋章，带上勋章可以获得属性，勋章放在背包即可获得属性
 可以设置一下type的作用，检查type,然后通过type类型的不同来定义不同的获得属性的方法
 还有给装备绑定粒子特效
 望能实现

**Comment by Arthur2e5** [comment]
Someone found your text to be in close resemblance with the *extra features* described in http://tieba.baidu.com/p/4261178992. So therefore, standard GPL + ￥￥￥ notice text:

1. RPGitem is licensed under GNU GPL, version 3. In Chinese, it's referred to GNU 通用公共许可证，第三版。Here are some key constraints set by this license:

  1. Every modifications you, as well as others, make to this plugin, are licensed under GNU GPL.
  2. When you give the compiled JAR to someone else, you need to give the source code you used to compile the JAR from.
  3. You must not erase our names and the link to our repository from the JARs. At least don't erase our names and emails.
  4. People you sell the JAR (and Java source code) to can give the JAR (and the source again) to others. For free. Without your specific agreement.
  5. If the copyright law is not happy with these statements of giving people rights to use the plugin, then GPL becomes *all rights reserved* automatically.

2. Don't worry, you can still sell this plugin. Actually, the guy who came up with the idea of GPL, Richard M. Stallman, created Emacs GPL to ensure his Emacs Floppy Drive and Discs:

  1. are protected by the Copyright law, and
  2. can become popular among people.

  Although the age of selling software discs has passed, with the current Internet condition (and perhaps your nice and warm support, ~~plus a little bit of foo-you~~), people might still be interested in buying the plugin from you.

Failure to adhere to any of the terms in GPL may take you to the world of boring lawsuits.

Buy the way I am not quite happy with the 半成品 statement.
