### ISSUE TITLE
Error occurred while enabling RPGItems v3.5.448 (Is it up to date?)

### ISSUE THREAD

**Issue by ErnestVlz** [NyaaCat/RPGItems-reloaded#447]
![Screenshot_1](https://user-images.githubusercontent.com/50779596/105785777-bc387500-5f49-11eb-9b58-85ae465b4dba.png)
![Screenshot_3](https://user-images.githubusercontent.com/50779596/105785786-bf336580-5f49-11eb-9cb4-89697306d26b.png)
![Screenshot_2](https://user-images.githubusercontent.com/50779596/105785790-c0649280-5f49-11eb-8fe5-88c3d5657cff.png)

I need help with this problem that appears on my server, I get this error Error occurred while enabling RPGItems v3.5.448 (Is it up to date?). java.lang.NullPointerException: null. How can I solve that?

**Comment by ReinWD** [comment]
#446 this may help you.

ver1.12 is no longer maintained.
