### ISSUE TITLE
我该怎样限定物品的使用方式？

### ISSUE THREAD

**Issue by chunye666** [NyaaCat/RPGItems-reloaded#449]
我创建了一个物品并且希望它能够像一个技能那样工作，这意味着我使用power来实现这一功能；

我发现了一个问题，正常使用技能是右键鼠标，但是玩家左键正常攻击也能出现我设置的伤害，这意味着玩家将能够把一个伤害很高的技能当作近战武器攻击；

我不希望出现这种情况，我希望能够限制伤害的触发必须是由技能（即右键实现power来造成伤害），而不是左键快速普攻就能够造成我设置好的伤害；

我在命令列表中没有找到相关命令，希望您能够提供我一些帮助。

**Comment by ReinWD** [comment]
如果是当前最新版本，请为物品添加 rangedonly marker。拥有rangedonly marker的物品无法使用近战攻击。
老版本物品请寻找与ranged/rangedonly相关的字段设置。具体的细则不好追溯。

**Comment by chunye666** [comment]
感谢您的回复！
补充说明：使用/rpgitem <[item]> power rangedonly 指令来限制物品只能够作为远程武器使用
加上这条之后物品对着生物/玩家左键将只有破空声却不会造成击退/伤害
