### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by Cuaris** [NyaaCat/RPGitems-reloaded#45]
With the new version all the players that hack rpgitems on their chest or other side are obsolete, doesnt work anymore. I have like 16,000 players with items in their chest, inventory etc.

Can you make that with the new version you "import" the old items to new? so the players can keep their items. Thnks.

**Comment by RecursiveG** [comment]
About the compatibility problem, please rollback to version v3.5.51 or before.
The commit introduced this problem (dcb3f4ac4162c1e271b0dab2efa1beae7ea22b33) is considered incomplete (You can still refer to the comment for imformation, however). 
A new NBT-based solution was made in the latest commit e4b687dc718ada75375d35c24ddd37918effea99 (v3.5.76). 
And here is the [Update Instruction](https://github.com/NyaaCat/RPGitems-reloaded/wiki/Update-to-NBT-based-item-identification)
An announcement will be made when the new solution get verified, it should be done soon.

**Comment by RecursiveG** [comment]
Please Follow these instructions to update the items. [Update to Lore based item identification](https://github.com/NyaaCat/RPGitems-reloaded/wiki/Update-to-Lore-based-item-identification)
And please use release [v3.5.80](https://github.com/NyaaCat/RPGitems-reloaded/releases/tag/master-v3.5.80) or later ones.
You have to **Restart** the server when updating the plugin. `/reload` may cause problems.
And the new lore-based items are compatible with old plugins which use displayName-based identification.
