### ISSUE TITLE
技能参数说明的语言文件无法正确读取，ActionBarTip没有正常工作

### ISSUE THREAD

**Issue by Tenkijino** [NyaaCat/RPGItems-reloaded#454]
# 问题反馈

## 描述你遇到的问题

使用 `/rpgitem power list` 或 `/rpgitem power prop {item}` 时列出的技能参数说明没有正确地从语言文件中读取  
全部返回null

于1.14的早期3.8版本ActionBarTip可以正常显示技能的参数说明  
当前版本此功能没有正常工作

## 截图

1. 于早期3.8版本正常工作的ActionBarTip
![1.png](https://i.loli.net/2021/02/11/laxEbjmdRIOWBPY.png)

2. 早期3.8版本中正确读取的语言文件
![2.png](https://i.loli.net/2021/02/11/8ZOafzeuHGrqbT9.png)

3. 当前版本中没有正确读取语言文件
![3.png](https://i.loli.net/2021/02/11/ZxOWi2T3Xg8twkL.png)

## 环境

- Java 版本：java 11 - 11.0.7
- 服务端版本：paper 1.16.5
- RPGItems 版本：rpgitems-1.16.4-3.8-16

**Comment by Clexus** [comment]
已修复
