### ISSUE TITLE
Problem with fresh installation

### ISSUE THREAD

**Issue by genysta** [NyaaCat/RPGItems-reloaded#455]
Hi, im quite new to minecraft server management and those plugin.
Im installing rpgitems just like the instruction but im getting this error. I can create item but when i use it, it deals no damage to mob. Im trying to get some command help but im getting no description and no usage information.

**Comment by genysta** [comment]
There's some MISSING LANG too, i've read FAQ but i cant understand what does it mean. Creating new dir called lang on RPGItems dir?

**Comment by ReinWD** [comment]
MISSING_LANG is an internal error when language file like en_US.yml don't contain correspoding string.
You can add it freely in language file and reload, most of them are harmless. Just missing of help strings.

language file is located at RPGItems/<your-language>.yml you can change your language in config.yml.

**Comment by ReinWD** [comment]
try 
/rpgitem damage <item>
/rpgitem power 
/rpgitem condition
/rpgitem marker
and use tab complete.

**Comment by genysta** [comment]
I'll try those and let you know whether it's work or not

**Comment by genysta** [comment]
For now i know these thing :
In restored world from my backup rpg item will not do any damage
In my new world / fresh world the rpg item work and deal damage

**Comment by ReinWD** [comment]
try to use a lower version of minecraft like 1.13, 1.14 and test if it works. We've tested upgrading version by version.
But structure of item has changed so much. I cann't say for sure.
