### ISSUE TITLE
Don't know how to control behavior and behaviorparams in Power Beam

### ISSUE THREAD

**Issue by Fatcat540** [NyaaCat/RPGItems-reloaded#456]
Hello,
I tried to change my item's behavior(power beam),
but it didn't seem to work(I have tried all possible behavior)
I know the problem must came from the behaviorparams
Unfortunately, I don't understand the description in wiki(about JONS).
Also, there's no description and bug warning showed up,
so I think I just need to know the format of behaviorparams for each behavior. 

- Java version：[ java -8 ]
- server version：[ 1.16.4]
- RPGItems version：[ RPGItems-mc1.16.4-3.8-24-release ]

BS :))

**Comment by Clexus** [comment]
Outdated
