### ISSUE TITLE
How can I modify the command history displayed in chat when tagging a player using a command from a power item?

### ISSUE THREAD

**Issue by mmop25** [NyaaCat/RPGItems-reloaded#459]
I apologize in advance for the sentences may be a little incomplete because I use a translator.
How do I remove the command history displayed in the chat window?
![asdsadasda](https://user-images.githubusercontent.com/86307152/122943984-6d84ef00-d3b2-11eb-86bf-0c97b5761b6c.PNG)

**Comment by Clexus** [comment]
Won't implement
But if you need a longer chat history, try [ChatPatches](https://modrinth.com/mod/chatpatches) mod
