### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by Cuaris** [NyaaCat/RPGitems-reloaded#46]
Im sure of this cause when i remove the plugin its fixed.

Players fill their inventory with trash and a chest too, then the players put 1 golden apple (or the item they want to duplicate) and 64 on 1 slot of the chest. They pick up the 64 and drop em to the floor, close de chest and when you pick up the 64 you have 128 in your inventory the original 64 + the 1 that you had its converted to 64. Any idea?.

**Comment by RecursiveG** [comment]
Cannot reproduce.
Please test with latest version. It may have been fixed.

**Comment by RecursiveG** [comment]
Old issue. Seem fixed according to [Ang_Drew](https://www.spigotmc.org/resources/rpgitems.17549/reviews).
