### ISSUE TITLE
Add PlaceholderAPI support

### ISSUE THREAD

**Issue by AlwaysReadyWBY** [NyaaCat/RPGItems-reloaded#462]
Sometimes the condition mechanic is not powerful enough. Is it possible to add a condition that matches strings and supports PlaceholderAPI?

**Comment by WitherVictor** [comment]
That's true . We LITERALLY need that

**Comment by phoenixlzx** [comment]
I've added this to the TODO list.

**Comment by Clexus** [comment]
Implemented in commit 68f6bee
