### ISSUE TITLE
RPGItems-3.8-27 道具属性更新（Attribute Update）和 自身状态效果（PotionSelf）问题 

### ISSUE THREAD

**Issue by luoxiawuchen** [NyaaCat/RPGItems-reloaded#467]
# Bug Report

## Describe the Bug

1、道具属性更新（Attribute Update）
物品设定为FULL_UPDATE状态后无效 仍有部分不同步
 - 展示名
 - damage的文字显示（属性同步了，但是描述没同步）

2、自身状态效果（PotionSelf）
如果设置了多个药水，每次右键只能生效0号位置的药水效果,即每次只能生效第一个添加的药水效果

## To Reproduce

none

### Stacktrace or log

If applicable, add stacktrace or log during the issue.

## Environment

- Java version: JDK16
- Server software version: 1.16.5
- RPGItems version: RPGItems-mc1.16.4-3.8-27-release.jar

## Additional Context
以上是BUG情况的汇报，感谢开发人员的耐心阅读

个人的一些心声：
RPGitem是一款极为强大的优秀插件，
我从1.6开服之初就开始使用了
尽管现在有很多新的物品插件问世，
但个人觉得仍然不如rpgitem这般简洁且强大
其地位在本人心中是超然的。
感谢NyaaCat社区对插件的接力
祝：rpgitem越来越好

**Comment by Clexus** [comment]
已修复
