### ISSUE TITLE
attack delay question

### ISSUE THREAD

**Issue by PlayingNuro** [NyaaCat/RPGItems-reloaded#468]
How to make damage proportional to the attack delay? I changed the damage from 7 to 8 and the item was an iron sword, but if I hit it ignoring the attack delay, it causes strong damage every time I hit it, which is a problem.

**Comment by Clexus** [comment]
Use evalDamage and its [attackCooldown](https://github.com/NyaaCat/RPGItems-reloaded/blob/b151f6eb23969df78a548b6dbc1c8c5e13e51ef6/src/main/java/think/rpgitems/power/impl/EvalDamage.java#L89) parameter
