### ISSUE TITLE
我在1.16.5的catserver无法使用1.16.4版本

### ISSUE THREAD

**Issue by Y-Yuw** [NyaaCat/RPGItems-reloaded#469]
![WV(0$P6~@D5~$%`Q0G0O504](https://user-images.githubusercontent.com/89560808/174293587-1aec3afa-4927-4d1c-a8ec-908639437b65.png)
问下是不是1.16.4无法在1.16.5的环境下使用？

**Comment by MossCG** [comment]
Install Nyaacore
显然 你没装前置Nyaacore
