### ISSUE TITLE
Help Repair items 

### ISSUE THREAD

**Issue by Barderoo** [NyaaCat/RPGItems-reloaded#470]
# I can't repair my RPG items

## I have no way to repair my RPG items

I need a solution, I'm looking for the player to spend a certain amount of money to be able to repair RPG items

- Java version: Lasted
- Server software version: Spigot 1.8X
- RPGItems version: v3.5.264
![imagen_2022-09-25_030126330](https://user-images.githubusercontent.com/114328166/192130561-114edcce-547f-43c5-a702-87382f51cfb5.png)

HELP ME PLEASE

**Comment by Clexus** [comment]
1.8 is not supported anymore
