### ISSUE TITLE
1.20.4不显示hand类型和type类型以及quality类型

### ISSUE THREAD

**Issue by 195527** [NyaaCat/RPGItems-reloaded#474]
# Bug Report

## To Reproduce

1.20.4不显示hand类型和type类型以及quality类型，物品只显示物品名字，伤害，技能描述和description，其他的不显示，功能正常

**Comment by Clexus** [comment]
quality对应的是物品颜色，请参照config.yml
hand和type在新版的rpgitem已不存在
