### ISSUE TITLE
1.12.2武器伤害无效

### ISSUE THREAD

**Issue by kecren** [NyaaCat/RPGItems-reloaded#475]
# 问题反馈
武器自定义伤害无效
## 描述你遇到的问题
插件正常加载情况下武器自定义伤害无效，均为原版伤害
清晰的描述你遇到的 Bug 或者问题。
我将我的服务器从备份下载回来后启动后，插件的武器伤害失效了，护甲也没有正常生效
## 重现问题

重现问题的步骤：

1. ……
2. ……
3. ……

### 预期行为

清晰、简洁地描述你预期的程序行为。

### 截图

如果合适，请附上截图以便更好地描述你遇到的问题。

### 日志

如果合适，请附上问题发生时的后台报错、日志。

## 环境

- Java 版本：[ java -version ]
- 服务端版本：[ /version ]
- RPGItems 版本：[ /rpgitem version ]

## 附加说明

可以在这附上其他相关信息。

**Comment by kecren** [comment]
> # 问题反馈
> 武器自定义伤害无效
> 
> ## 描述你遇到的问题
> 插件正常加载情况下武器自定义伤害无效，均为原版伤害 清晰的描述你遇到的 Bug 或者问题。 我将我的服务器从备份下载回来后启动后，插件的武器伤害失效了，护甲也没有正常生效

**Comment by Clexus** [comment]
1.12.2的版本不再维护
不过如果你需要帮助，请附上物品文件和日志
