### ISSUE TITLE
Beam freezes along tick

### ISSUE THREAD

**Issue by Bw32** [NyaaCat/RPGItems-reloaded#479]
The particles do not generate when tick is frozen, but the beam moves independent of the tick. Seems like the beam moves with its own timer.

https://github.com/user-attachments/assets/b62c07ff-fc89-4035-9edf-cda008557537

**Comment by Clexus** [comment]
Sorry, but we don't accept issues caused by `/tick freeze`
The beam power runs independently of Minecraft's vanilla logic, so it works as expected. However, particle rendering will be completely paused, which is an anticipated behavior and therefore cannot be considered a bug.

**Comment by Bw32** [comment]
Hope this can be added as a feature in the future, as this would compliment with beam really well.

**Comment by Clexus** [comment]
> Hope this can be added as a feature in the future, as this would compliment with beam really well.

It's not possible due to the vanilla restrictions
