### ISSUE TITLE
Consider using real properties files for locale

### ISSUE THREAD

**Issue by Arthur2e5** [NyaaCat/RPGitems-reloaded#49]
Context for this issue: https://github.com/NyaaCat/RPGitems-reloaded/commit/f9ad3da#commitcomment-15697098

Commit f9ad3da shows a dirty transformation from Transifex's real `.resources` output to the `.lang` format currently being used in RPMitems. This is caused by the fact that Transifex doesn't supports the `*.lang` k-v format, and whoever created the transifex repo found it best to approximate with the [Resources][prop-load-rdr] format.

Need for such extra transformations cause inconvenience -- maintainers have to do some `sed` job on the files pulled from Transifex before committing it to the tree. This also makes some Transifex auto-import useless. Likewise, pushing to Transifex may require similar extra care to re-escape the strings.

Therefore, I guess it's better to switch to the real resource and let [`Properties.load(Reader)`][prop-load-rdr] do the job. This also allows people people to use some backslash escapes, for, e.g. newlines. Some type conversion tips are available at https://stackoverflow.com/questions/17209260.

[prop-load-rdr]: https://docs.oracle.com/javase/6/docs/api/java/util/Properties.html#load(java.io.Reader)

**Comment by Arthur2e5** [comment]
This is how it might look like (Well I don't write Java…):

```Diff
--- lo.j        2016-01-27 01:25:31.951059900 -0500
+++ Locale.java 2016-01-27 01:33:28.957728700 -0500
@@ -26,6 +26,7 @@
 import java.io.UnsupportedEncodingException;
 import java.util.HashMap;
 import java.util.Map;
+import java.util.Properties;

 import org.bukkit.Bukkit;
 import org.bukkit.ChatColor;
@@ -91,22 +92,11 @@

     private HashMap<String, String> loadLocaleStream(InputStream in, HashMap<String, String> map) {
         try {
-            BufferedReader reader = new BufferedReader(new InputStreamReader(in, "UTF-8"));
-            String line;
-            for (line = reader.readLine(); line != null; line = reader.readLine()) {
-                line = line.trim();
-                if (line.startsWith("#") || line.length() == 0) {
-                    continue;
-                }
-                String[] args = line.split("=", 2);
-                if (args.length == 2) {
-                    map.put(args[0].trim(), args[1].trim());
-                } else {
-                    Plugin.logger.warning("Unknown lang line: " + line);
-                }
-            }
+            Properties loc = new Properties();
+            loc.load(in);
+            map.putAll((Map) loc);
             return map;
-        } catch (UnsupportedEncodingException e) {
+        } catch (IllegalArgumentException e) {
             e.printStackTrace();
         } catch (IOException e) {
             e.printStackTrace();
```

I am using Properties.load(inputStream), which is also available in JavaSE 6. Should I try getting myself in the AUTHORS list by sending a PR?

Additionally, according to `load(Reader)`:

> The key contains all of the characters in the line starting with the first non-white space character and up to, but not including, the first unescaped '=', ':', or white space character other than a line terminator. 

It appears that escaping is only necessary for keys in this format, so the old files will still work.

**Comment by Arthur2e5** [comment]
So with 03a19c3 it looks like you are going to move to yml… Not bad.

But again (#51), try not to waste the old translations. Import these now so they get kept in the TM.

**Comment by RecursiveG** [comment]
@Arthur2e5 Could you please take charge of the Transifex team join requests and make necessary changes to the languages listed?

**Comment by Arthur2e5** [comment]
I can't. That's the *project* manager's job. I can only manage the *team*.

**Comment by phoenixlzx** [comment]
@Arthur2e5 You are now one of the project managers.

再丢锅就塞卷

**Comment by Arthur2e5** [comment]
我要吃情人节卷！
