### ISSUE TITLE
Unknown attribute 'generic.attackDamage'

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#5]
I found the following warning shows up in console when player uses some weapons with customized attack damage.

```
Ignoring unknown attribute 'generic.attackDamage'
```

**Comment by Taiterio** [comment]
Thought that this error would occur when the damage of an item is set to be negative, but in the end I cannot find a way to recreate the warning. I also couldn't find any posts on Bukkit/Spigot containing this warning. Will get some people to test around on a server and check if it results in the warning showing up.

**Comment by RecursiveG** [comment]
More log required. Also wonder how to reproduce.
It may not be a bug of RPGItem since attributes like this are handled by minecraft.

**Comment by phoenixlzx** [comment]
There's no more log in the console. Maybe we should add a 'debug mode' to help find bugs?

Also, other plugin may cause this problem as well. Keep this issue open and wait temporarily.

**Comment by phoenixlzx** [comment]
This issue seems to be not related with RPGitems, it's caused by summon commands.

Closing issue.
