### ISSUE TITLE
Some messages like these in rpgitemupdate are not localized.

### ISSUE THREAD

**Issue by Artoria2e5** [NyaaCat/RPGitems-reloaded#50]
Although it does sound silly and clumsy, but in Java with some resourcebundle-like way of localization you always have to come up with a name (hashtable key) for all these message strings and put them in the en_GB file.

/\* Now I understand why people like gettext. */

**Comment by Arthur2e5** [comment]
No, no, no, that's not all… Hey…

**Comment by Arthur2e5** [comment]
Hey Hey Hey Hey Hey!
Check for ALL string literals before closing!

**Comment by RecursiveG** [comment]
Well...

**Comment by Librazy** [comment]
We have a compile-time checker now
