### ISSUE TITLE
Please remove zh (Chinese) from Transifex

### ISSUE THREAD

**Issue by Arthur2e5** [NyaaCat/RPGitems-reloaded#51]
It's common knowledge that simply `zh` means nothing, and we do have zh_CN, zh_TW and zh_HK.

Same for English (en).

And if you do want translators to get interested, do not disappoint them in the first place. Add all the languages found in https://github.com/NyaaCat/RPGitems-reloaded/tree/master/src/main/resources/locale to Transifex, and use *upload translations* to upload all the `.lang` data so everyone can see a good progress bar.

**Comment by RecursiveG** [comment]
cc @phoenixlzx

**Comment by phoenixlzx** [comment]
Removed.

**Comment by Arthur2e5** [comment]
Looks like many of the lang files are just direct copies of the en_GB file……I should do some diff someday to figure out which of the languages are actually translated.

By the way can't we just switch to en_US as the base lang?

**Comment by phoenixlzx** [comment]
@Arthur2e5 Go ahead.

There are many old translation files could be imported as well.

**Comment by Arthur2e5** [comment]
Many of them look like just the same as en_US. zh_TW might be worth still importing though.

I think I should do a for loop in shell and run some diff…

**Comment by RecursiveG** [comment]
You may reopen this issue if you need to.
