### ISSUE TITLE
Duplication & infinite use on consumables

### ISSUE THREAD

**Issue by hjklr54679** [NyaaCat/RPGitems-reloaded#52]
When crafting, giving, or even picking up items with a consumable ability, the item appears to not be consumed and, while the ability will keep activating, will switch between 2 inventory slots allowing infinite use and the player can press 'q' in the empty inventory slot to make a separate, duplicated non-ghost item of the same type appear on the ground. I will try isolating the plugin to see if the issue persists or if it is an incompatibility.

**Comment by RecursiveG** [comment]
Can you give a concrete example of an item and the detailed steps to reproduce the problem?

**Comment by hjklr54679** [comment]
Okay. Upon testing it on a server with no other plugins, the error still persists. Here is the item I am using: http://pastebin.com/bDvhnf4D
It appears to make the item disappear client-side, however not server-side when using consume.

**Comment by hjklr54679** [comment]
Actually, after doing some further testing, it appears to only affect swords when used with the consume ability. Not much of a major problem.
