### ISSUE TITLE
2 Power Bugs

### ISSUE THREAD

**Issue by Ted2001GR** [NyaaCat/RPGitems-reloaded#55]
Hello 

One Bug With Fire Power Cooldown i do /rpgitem test power fire 200 5 5 For Example And The Couldown Is For 0.8 Sec If I Put 0 Cooldown It Will HAve Again 0.8 Sec Cooldown

Another Bug With Projectile Power If I Type /rpgitem test projectile snow it is ok but If a put another argument like cooldown  Range And Amount It WIll BE Show Me The Message TO Put A Right Projectile 

Sorry For MY Bad English And These Bugs IS 100% Bugs OF THe PLugin And Not From My falt 
BTW I LOVE YOUR NEW RPGITEM PLUGIN KEEP THIS UPDATE PLSS :) GOOD WORK!

**Comment by RecursiveG** [comment]
Please try the LATEST build.
