### ISSUE TITLE
Make a power to show particles

### ISSUE THREAD

**Issue by Ted2001GR** [NyaaCat/RPGitems-reloaded#56]
Can You Make A Power That Put Particles In RPG??
For Example /rpgitem test power particle flame??
Because There Are No Permission To Give To Members To Access Them For Command Powe

(Sorry For My Bad English) Your Plugin Is Amazing ^^ Keep Your Amazing Work

**Comment by phoenixlzx** [comment]
+1 on this.

Options should include: practicles type, enable mode (hold, rightclick or leftclick), and duration and cooldown if set to click.

**Comment by RecursiveG** [comment]
@phoenixlzx 
You can have an effect played multiple times with an interval, but you can not make an effect "durable". So what do you mean here?
Also, the "hold" trigger looks confusing for the same reason. Playing the effect every tick may significantly lag the server.

**Comment by phoenixlzx** [comment]
@RecursiveG Duration only applies when it set to click to use, means the effect lasts for some time after left or right click.

For hold, just give the player unlimited time of effect once, and when player switch to another item, remove the effect.
