### ISSUE TITLE
Big list of suggestions, from my server staff and myself

### ISSUE THREAD

**Issue by hjklr54679** [NyaaCat/RPGitems-reloaded#58]
**I believe some of these features would be very useful for server owners and admins like myself when using this plugin:**

Command aliases. Rather than doing /rpgitem pbgun give, this would allow you to do /ri pbgun g instead.

Triggers for powers. Ex. on right click, left click, when hit, damaged, when sneaking, on kill, on killed, when consumed, when breaking a block, when the item breaks, etc.

Custom furnace recipes and shapeless recipes.

Easier config-based item creation. It would be a lot better if there was an easy, reliable way to create items using the config rather than have the plugin reset the config if you mess up.

Compatibility with essentials kits and other plugins such as Mythicmobs.

Custom displays for all power types, rather than just command.

**And some optional stuff that we believe might help:**

Custom attack speed and range

Critical hits & chance to dodge with custom % values

More powers, such as "backstab" and "message"

A skill like durability but for right clicking/using a certain power. For example, a pistol that, when shot, loses durability and eventually breaks.

A skill that removes an item from your inventory on use, and if the player doesn't have said item, will prevent other skills from activating.

**And any other essential features in a certain plugin that hasn't been updated in months starting with a "More" and ending with an "Items".**

**And yes, I know I'm asking WAY too much out of the plugin dev. I'm not saying even 1/3rd of these could make it in, these are just the things that would be nice to have.**

**Comment by RecursiveG** [comment]
Thank you for these amazing suggestion. But the main focus on this plugin is to fix bugs and to make it compatible with latest bukkit.

Some features cannot be implemented easily due to how the old codes are structured. But I'm writing a new plugin (See #34). I'll definitely take your advises into consideration.

**Comment by SlappyAlpaca** [comment]
**For easy config, I recommend looking at Mythic Mobs for inspiration.**
    http://dev.bukkit.org/bukkit-plugins/mythicmobs/files/62-mythic-mobs-v2-2-0/
