### ISSUE TITLE
arrow effect with big damage can cause crash

### ISSUE THREAD

**Issue by chenxuuu** [NyaaCat/RPGitems-reloaded#60]
When I use it attack player or other animals,the server went crash.

I think it is caused by arrow effect with big damage.

the item data is below:
  cx:
    name: cx
    id: 1
    haspermission: false
    permission: a.default.permission
    display: 'test'
    quality: LEGENDARY
    damageMin: 99999999
    damageMax: 99999999
    armour: 0
    type: Sword
    hand: One handed
    lore: ''
    description: []
    item: TNT
    ignoreWorldGuard: false
    item_data: 0
    powers:
      '0':
        powerName: arrow
        cooldown: 1
      '1':
        powerName: potionhit
        chance: 1
        duration: 9999
        amplifier: 100
        type: SLOW
    recipechance: 6
    hasRecipe: false
    dropChances: {}
    maxDurability: -1
    forceBar: false

**Comment by phoenixlzx** [comment]
max valid damage is 32767, this should have a limit check. cc @RecursiveG

**Comment by chenxuuu** [comment]
@phoenixlzx You are right.....诶、原来是这样。。。
