### ISSUE TITLE
Request: Ability to remove the lore that the plugin puts on the items.

### ISSUE THREAD

**Issue by whoshenry** [NyaaCat/RPGitems-reloaded#62]
I'd like to remove the lore the plugin puts on the item so the items you create are fully customisable as at the moment, the format of the lore doesn't fit with other items I have on the server.

This is the section I'd like to be removed - http://prntscr.com/a10qku

**Comment by RecursiveG** [comment]
Do you mean different lore for each item given to players?
It's hard to achieve because RPGItem will automatically restore lores to default when items are used.
It's also the reason why rpgitems cannot be enchanted.

**Comment by whoshenry** [comment]
Yeah I suppose I do.

Basically I want to create an item with all of the powers or characteristics of RPGItems but with FULL control of the lore so I don't have to have what is highlighted in the red box in the print screen above.

I suppose this can be achieved by the full identification of the lore and the name in the config, similar to how Mythic Mobs identifies their items.
