### ISSUE TITLE
Item Permission

### ISSUE THREAD

**Issue by Atracador** [NyaaCat/RPGitems-reloaded#63]
Could you implement a feature where without the necessary item permission you can't craft/use the specified item, i've been trying to separate items between worlds but none of the current RPGItems have the per item permission option. Thank you for reading! Have a nice day! :smile:

**Comment by RecursiveG** [comment]
Thank you for your reply and we will try to implement this.
Duplicate with #8 
Keep an eye on that issue.

**Comment by RecursiveG** [comment]
try this command
`/rpgitem {itemName} permission {permissionNode} {requirePermission(true/false)}`
When set to `true`, only players have `{permissionNode}` can use that item.
