### ISSUE TITLE
PotionTick not works with effects like regeneration

### ISSUE THREAD

**Issue by zwa73** [NyaaCat/RPGitems-reloaded#66]
rt弄个无限生命回复的都不行，倒是我不知道现在最新版本有没修复，因为全部下不了QAQ

**Comment by zwa73** [comment]
RPGitems-reloaded-v3.5.84.jar 这个版本

**Comment by RecursiveG** [comment]
ref: 84ce55291490126a7333a49c2655ac2f8b86a92e

**Comment by RecursiveG** [comment]
This bug should have been fixed in 84ce55291490126a7333a49c2655ac2f8b86a92e
