### ISSUE TITLE
description 这指令的字体颜色问题

### ISSUE THREAD

**Issue by zwa73** [NyaaCat/RPGitems-reloaded#68]
description:
    - '&f1'
    - '&f&21'
    item: WOOD_SWORD
不管怎样一定会带个&f的颜色
然而因为potiontick的问题我希望改成这样
    description:
    - '&6Effects:'
    - '          &9REGENERATION &f1'
必须得到item里面手动改了

**Comment by zwa73** [comment]
额对了还有空格也不能加
上边那个regeneration前面本来有10个空格的但是好像被网站弄掉了
希望能加上像power command指令里的··符号留空功能

**Comment by RecursiveG** [comment]
不认为这是个问题。你最好详细解释下。

Can't get your point. Explain it more please.
