### ISSUE TITLE
New fire power

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/RPGitems-reloaded#7]
This is a new fire power idea, I have posted under custom enchantments before.

To simplify, item with this power shoots fire and set several blocks (configurable) in front of the player on fire just like rumble power, and burn all enemies on the way for some time (configurable). The fireblock will remove itself after a specified time.

**Comment by Taiterio** [comment]
Added in commit 13175267b92b10bf50d9f8687d6db00121444601. If you have any wishes/changes to it, then feel free to reopen this :)

**Comment by phoenixlzx** [comment]
Please remember to update those changes to wiki to make the plugin easy to use.

**Comment by Taiterio** [comment]
Updated the wiki to include the latest powers :)
