### ISSUE TITLE
PotionSelf not extends effective time of existing effects

### ISSUE THREAD

**Issue by zwa73** [NyaaCat/RPGitems-reloaded#70]
只有前一个改成0才能一起起效
同样不知道新版本有没好

**Comment by zwa73** [comment]
哦还有这个potionself不能覆盖之前的效果
比如设置一个一次性物品，使用给10秒的生命恢复，冷却0
用了一个之后在还剩5秒时在用一个那效果不会变回10秒

**Comment by RecursiveG** [comment]
potionself的cooldown是算一起的，所以就是把第一个cd改成0好了。
