### ISSUE TITLE
改武器伤害显示的颜色

### ISSUE THREAD

**Issue by zwa73** [NyaaCat/RPGitems-reloaded#72]
好像目前只能是白色？

**Comment by RecursiveG** [comment]
请详细解释下

Not sure what you are talking about. Please explain it more.

**Comment by zwa73** [comment]
就是rpgitem test damage 10
然后这不是会显示一个damage 10么还有各种power之后武器上的信息不能改颜色
差不多就是请求功能了？

**Comment by RecursiveG** [comment]
In favor of #62 
But won't address that in the near future.
