### ISSUE TITLE
请求新功能 格挡/闪避

### ISSUE THREAD

**Issue by zwa73** [NyaaCat/RPGItems-reloaded#76]
就是手持时一定几率免疫一定量伤害和一定几率免疫一定百分比伤害
和以前那个属性标签一样

**Comment by zwa73** [comment]
就像伤害吸收和抗性提升

**Comment by Taiterio** [comment]
#59 also suggested this :)

To keep with the overall theme, such attributes would have the general names like Block/Reflect. For thematic effect, these Attributes could be renamed for Sword to be Parry/Riposte

**Comment by Clexus** [comment]
Use attributes plugin for this
