### ISSUE TITLE
Detailed permission control required

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/RPGItems-reloaded#8]
This is only one permission node `rpgitem` currently.
Add more nodes so that we can have detailed permission control.

**Comment by Taiterio** [comment]
Added command permissions in commit c7ed446ad99e728f64894435c07c5d4ab00635ba. The way they now work is that a player requires one of the following three permissions to use a command:

rpgitem - the main permission node for the plugin
rpgitem.command - the permission node for all commands
rpgitem.command.[commandname]

For the nodes, I was unsure whether to use an * for them or not, but seeing as the one present right now did not use one, I left it out.

For further permissions: I saw that items already have a way of having permissions attached, although I think that reworking those to use the format rpgitem.item.[itemname] would be a better way of handling such permissions, but I'll wait on your input on that :)

Beyond that, do you have any more areas where you would like to have more permission control added?
