### ISSUE TITLE
World Guard Flag

### ISSUE THREAD

**Issue by Ted2001GR** [NyaaCat/RPGitems-reloaded#82]
Can You Make A Custom World Guard Flag That Enable Or Disable RPGItems? Because In Some Regions We Want RPG Items Enable But Not PvP Such As A Monster Area!! Thank You!!

**Comment by cyilin** [comment]
added custom flag in commit b1c99a3
@RecursiveG  Now we need to add a command
Like `/rpgitem wgflag [region] [world] [allow/deny/remove]`
And change to use WorldGuard.canUseRPGItem() check permission.

**Comment by Librazy** [comment]
You can disable some or `all` power per region now.
