### ISSUE TITLE
In 1.9 releases, attack damage should be affected by vanilla cooldowns.

### ISSUE THREAD

**Issue by hjklr54679** [NyaaCat/RPGitems-reloaded#84]
Spam attacks currently will do the same amount of damage with custom items as it would with a charged attack in Minecraft version 1.9. I suggest adding an option in the config to enable custom weapons to coincide with the vanilla weapons in terms of how the combat works. An attack speed option for items would help as well although not needed.

**Comment by Librazy** [comment]
You can set an item's damage mode to VANILLA (item's damage in vanilla minecraft) in 1.11 version and use nbt to control the damage. We will support MULTIPLY mode (item's damage in vanilla minecraft multiply with RPGItem damage). Use ```rpgitem [item] damagemode``` to switch between them.
