### ISSUE TITLE
Looking for part of code that controls lore for item powers

### ISSUE THREAD

**Issue by hjklr54679** [NyaaCat/RPGitems-reloaded#85]
I'm not a very experienced coder myself, and I was just wondering where in the code item lore for powers is controlled because I was looking to remove it as I would prefer just to use the custom lore for items rather than default power lore. I've tried removing it from the language files, but that just leaves an empty line which looks very strange and out of place. The lines I'm talking about: http://prntscr.com/ahpgda

**Comment by RecursiveG** [comment]
They are defined in `displayText()` of each `Power` class. [Power.java#L44](https://github.com/NyaaCat/RPGitems-reloaded/blob/master/src/main/java/think/rpgitems/power/Power.java#L44)
And the final lore is constructed from [RPGItem.java#L481](https://github.com/NyaaCat/RPGitems-reloaded/blob/43cab3e8900c0c43a7c46ee474aec5f75f68509f/src/main/java/think/rpgitems/item/RPGItem.java#L481)

**Comment by hjklr54679** [comment]
Thank you.
