### ISSUE TITLE
[BUG] Transitioning to RPGItems Reloaded Breaks Recipes

### ISSUE THREAD

**Issue by Formula350** [NyaaCat/RPGitems-reloaded#87]
-This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) 
-RPGitems v3.5.100 *(I have not updated to the latest yet)* 

After upgrading to the Reloaded version of RPGItems we have discovered that the recipes no longer function as intended, as instead of producing the RPGItem, it produces the vanilla item that is set:
![item recipe-1](https://cloud.githubusercontent.com/assets/10291023/14030602/d50033da-f1de-11e5-9c4c-1779c9a5b6cb.jpg)

It's clear that the plugin DOES register the recipe, given it produces something, and checking the recipe set reflects that:
![item recipe-2](https://cloud.githubusercontent.com/assets/10291023/14030604/d880ec8e-f1de-11e5-9cc0-3dd726515311.jpg)

That's when I discovered that by checking the Recipe, it actually fixes the item and it becomes craftable!
![item recipe-3](https://cloud.githubusercontent.com/assets/10291023/14030607/db936b40-f1de-11e5-8a46-008fc3c58e9f.jpg)

We have roughly 400-500 items, and I suspect at least 1/4 of them have recipes. If there's a fix for this, I'm sure it'll save other servers the headache, though I'll just have to manually go through them all for now :P

**Comment by RecursiveG** [comment]
Did you set a chance to the recipe?
The chance feature may cause this.
Try taking the ingredients out of the table then put them back. The result should vary.

**Comment by Formula350** [comment]
Oh... Interesting, I did not know that was a new feature now!

Ok, well that does change things a **little**, but I'll explain the most basic method of how we would create an item with a recipe in the *old* RPGItems 3.4 (aka 3.0.4)...

/rpgitem furball create
/rpgitem furball display &6A &eGross &7Furball
/rpgitem furball lore The result of NyaaCat's excessive preening!
/rpgitem furball item firework_charge
/rpgitem furball damage 10 15
/rpgitem furball recipe
*<place recipe items in a pattern, close menu>*
DONE

What is of note is that the command we used was **/rpgitem <itemname> recipe**. When I attempted to use that command on v3.5.100, it kept coming up with the Help text, and that is when I noticed it would display the "CHANCE" option. So I figured I'll just use 1 (since that generally is 100% in RPGItems), and the Recipe Menu showed up.

*However*, the key here is that we never used the Chance option before, and so it seems that 3.5.xx is imposing its own Chance of 0% if an item lacks a Chance % previously.

**ALSO**, I don't know if this is related or not, but I just received word from one of my Admins that the Quests plugin had delivered the reward (which we have set as executing the RPGItem Give command) as a vanilla item. This item is only obtainable by completing this quest, and so it has NO recipe.

**Comment by RecursiveG** [comment]
OK, I see. The default recipe chance is 6. ([RPGItem.java#L82](https://github.com/NyaaCat/RPGitems-reloaded/blob/master/src/main/java/think/rpgitems/item/RPGItem.java#L82)) And I'm afraid that has been written to the configure file. So I can really do nothing about it from the code.

However, you can go to `items.yml` and manually find/replace all `recipechance: 6` to `recipechance: 1`. Do not modify the file when server is running and remember to backup. I think this will work.

As to the give command problem, if you can reproduce it, please open a new issue.

**Comment by Formula350** [comment]
I'm having issues reproducing the issue, but it seems to have happened once or twice now. I'm only hearing about the issues indirectly, and most people are assuming it's a problem with Quests, thus figure **everyone** is experiencing the same problem, *and* that we're working on it to correct the problem. 

I'll probably have to send a server-wide mail to let all the players know, if they are experiencing these issues to please report them to a staff member.

Is there currently any message that is sent to the ***player*** if an attempt was made at giving them an item, and their inventory was full? If no system is in place currently, would it be possible to integrate it? Just something like the global WorldGuard on/off command. I figure then as the message something simple: "You were unable to receive <display name> because your inventory was full."

 I could expand further, but then it'd get complex lol Like being able to set command/s to send a message to Ops, or a specific few (which I figure a custom command would work best since not everyone may use Essentials and thus have /mail send). Alternatively, a delay that is announced to them, before it re-attempts giving them the item. Appending the message to the above's "Please make 1 inventory slot available; second delivery attempt in 30 seconds."

I'll try to gather as many reports as I can regarding failed attempts made. Since Quests doesn't appear to make any entry in the console log, I can't provide any further info. I'll also check and see if there's a Debug mode in the Quests config that can do that though.

**Comment by RecursiveG** [comment]
Close this. 
Open a new issue about the Quests item rewarding problem if you want.
