### ISSUE TITLE
[BUG / REQUEST] Lava and Citizens2 NPCs Break 'Infinite/-1' Durability Armor

### ISSUE THREAD

**Issue by Formula350** [NyaaCat/RPGitems-reloaded#88]
-This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
-RPGitems v3.5.100

This issue has plagued RPGItems for quite a long time, and yet seems like RPGItems had the groundwork laid to utilize the vanilla "Unbreakable" meta flag, which would totally prevent this from happening (based on my tests).

**The bugs :beetle::** For the *Lava* issue it is usually a situation where a player is wearing an item that doesn't have a high durability to start with, things like Leather and Gold. Then they end up falling into Lava, sometimes continually due to being clumsy when using /back (we **do** have SafeTP turned on). The only thing I can guess that happens from there is simple a result of the items low natural durability being depleted faster than RPGItems is able to keep up with "repairing" it, ultimately leading to the item breaking. It has happened enough where we had to place signs at Spawn warning players to not be negligent and wade through lava.
For the *NPC* issue, it has to do with the fact we use the Sentry addon to make Boss NPCs for the players to fight (to complete quests). While we don't generally give these NPCs a very high damage, they still manage to wreck armor quite easily. Again, a problem that eventually resulted in warning signs being placed at all the Boss warps, which limited the difficulty level we could give these NPCs since players generally had to fight with their armor stored. 

**The Request:** However, eventually I created an armor that was completely vanilla, utilizing the Unbreakable flag '{Unbreakable:1}', and that item is impervious to taking a bath in lava as well as anything an NPC is able to dish out! I'm really hoping that this can be substituted into RPGItems in place of the "Infinity" (aka -1) durability option, providing **truly** infinite durability on items. 

As for why I feel as though this was a feature that ThinkofDeath and/or TheCreeperOfRedstone were going to add is due to these (which can be found [here](https://github.com/NyaaCat/RPGitems-reloaded/search?q=unbreakable&type=Code&utf8=%E2%9C%93))

src/main/java/think/rpgitems/power/PowerUnbreakable.java 
```java
25       public class PowerUnbreakable extends Power implements PowerHit {
…	
45	    public String getName() {
46	        return "unbreakable";
47	    }
48	
49	    @Override
50	    public String displayText() {
51	        return ChatColor.GREEN + Locale.get("power.unbreakable");
52	    }
53	}
```
And then all of these, which in addition to pointing out Unbreakable, seem to also illustrate that there was supposed to be an Unbreaking power. Based on the Locale string seems to indicate it'd be used for items that were set to have a durability; thus, Unbreaking would simple act like the enchant.
src/main/resources/locale/en_GB.lang 
```java
100  command.rpgitem.unbreakable=Adds the unbreakable power to @[Item]#. The unbreakable
         power prevents the item from breaking
101  command.rpgitem.unbreaking=Adds the unbreaking power to @[Item]# with a default level of 1.
         The unbreaking power works similar to normal unbreaking
```
src/main/java/think/rpgitems/config/Update03To04.java 
```java
7	import think.rpgitems.power.Power;
8	import think.rpgitems.power.PowerUnbreakable;
9	import think.rpgitems.power.PowerUnbreaking;
…	
23	            while (it.hasNext()) {
24	                Power power = it.next();
25	                if (power instanceof PowerUnbreakable) {
```

Any details I can provide to help, let me know!
-Form

**Comment by RecursiveG** [comment]
try `/rpgitem {itemName} power unbreakable`
This should set the Unbreakable NBT flag to items.

**Comment by Formula350** [comment]
Yea, I've tried that, has never worked. "Unbreakable" power doesn't show up in the Help list, either, never has. :(

Do I need to be running v3.5.101? As typing your command just results in:
25.03 23:01:47 [Server] INFO Showing help for 'power'
and then the whole list of all the various "Power" commands (same as it always has).

**Comment by RecursiveG** [comment]
try build v3.5.102

**Comment by Formula350** [comment]
Do you all have a Jenkins server to get dev builds from? Otherwise I'll have to wait for it to be approved on Spigot, which is fine as well :)

Thanks!

**Comment by RecursiveG** [comment]
All commits will be automatically built and added to the [Release Page](https://github.com/NyaaCat/RPGitems-reloaded/releases) immediately after being pushed.

**Comment by Formula350** [comment]
Awesome, I had looked around on Git for that sort of page, but apparently I'm just inept and blind :)

The command does indeed work now, just needs to be tested for certainty that it can hold up to NPCs, but I'm sure it will.

Some requests:
 - Option to define if it is listed in the Power section, or Description section or the Lore
 - Option to set Lore Entry color
 - Option to enable or disable its Lore Entry entirely *(at the very least, as then I can add it manually to description)*

Much appreciated for the help!
