### ISSUE TITLE
[BUG] mcMMO's Special Right-Click Abilities (Enchants) Become Stuck On Tools

### ISSUE THREAD

**Issue by Formula350** [NyaaCat/RPGitems-reloaded#89]
- This server is running CraftBukkit version git-Spigot-db6de12-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
- RPGItems 3.5.102

Massive issue occurring with RPGItems, caused by mcMMO's abilities, which are activated by right-clicking. 

Easiest means of reproducing would be to make any item, set Durability to -1, make it a Spade or Pickaxe, then right-click and start mining. When the ability wears off, the enchant should remove itself, but it doesn't as for some reason RPGItems isn't allowing modification a second time (or something?)

This problem becomes compounded every time you use your Ability. I took a shovel off a kid that had a level **65** Efficiency, because every time he used the Gigadrill ability, it would add +5 Efficiency.

This issue does not occur with vanilla items, **only** with RPGItems. 
I have not seen this happen with any weapons, and the Axe's mcMMO Ability seems to not be enchant based; thus, does not apply anything. The only two tools I've found it to affect are: Pickaxe, Spade
(can supply screenshots if needed)

**Comment by RecursiveG** [comment]
Are there any warnings or errors in the console?

**Comment by Formula350** [comment]
Nope :( I'd have made sure to post them. It's extra weird because it's not writing the enchant into the file, yet it's still managing to both continue to be an RPGItem (unlike if our players are a derp and rename their item) **and** the enchant is indeed working on these items.

We've been using RPGItems since 2013 and have kept up with the versions... The only thing I can think of it pertaining to is that when CreeperOfRedstone made his spinoff, in v3.5 he had added the ability for Enchanting of items (form my understanding, which is why we stuck with v3.4). However, in this revival of the plugin I noticed in one of the Closed issues that a fix was added to prevent the RPGItems from being enchanted by simply blocking them at the Enchantment Table.... 

Aaand I just came up with a way to confirm my theory, which upon testing it I can confirm my suspicions!

It would seem that indeed, the enchant ability was left in place, but the Enchantment Table block is enough to prevent players from applying them. ***However***, using /enchant on an RPGItem does work, is persistent, and does for the most part work from my small bit of testing. Things like Infinity on a bow work fine, so do others, EXCEPT for damage modifying enchants that are on Swords. *(Which that might help narrow down why Strength (Increased Damage) doesn't work on RPG Swords.)*

In lies the problem... We're sort of seeing a number of benefits to having it so we can enchant the RPGItems, particularly things like Infinity and Punch/Knockback, Depth Strider, etc.**So**, is there any way to target just mcMMO to have it monitor when it applies an enchant to an RPGItem, to have it only remove *those* enchants after the mcMMO Ability runs out (or a period of time)?

If not and they have to go-away entirely, I understand. Would honestly much rather have that fixed :)
(sorry if this is fragmented in thoughts, I've been typing this periodically over the last couple hours)

**Comment by RecursiveG** [comment]
It seems mcMMO will check a special lore text before removing the enchantment.
RPGitem will restore the lore when item is used thus makes mcMMO failed to remove the enchantment.
Try the latest build.

**Comment by Formula350** [comment]
Alright the mcMMO issue with the ability's enchants remaining is indeed resolved... However, now RPG weapons will not pass right-clicks to mcMMO at *all*. For example, while using a sword it used to activate Serrated Strike, now nothing occurs except the RPG power (if it has one).

I don't know if this is something that's addressable or not, though?

**Comment by RecursiveG** [comment]
Please open a new issue in this case. You can refer to this one using `#89` if you think these bugs are related.
