### ISSUE TITLE
Remove use of deprecated functions

### ISSUE THREAD

**Issue by RecursiveG** [NyaaCat/RPGitems-reloaded#9]
Replace the calls to deprecated functions with new ones.
Avoid potential incompatible.

**Comment by Taiterio** [comment]
Changed in commit cc558b62cc9c6da95810a1ccff582a568ebc4f6d. Upgraded deprecated function calls where possible, added supressions for deprecation warnings for functions which seem to require the usage of deprecated functions. 

@RecursiveG, sorry for unassigning you, thought multiple people could be assigned and I had already changed the deprecated functions already :/

I'll leave this issue open so you can check if any of the warnings for deprecation I surpressed have an easy way to be fixed, feel free to close it :)
