### ISSUE TITLE
"/rpgitem [ITEM] durability togglebar" Does not Work (Bar is Always Shown)

### ISSUE THREAD

**Issue by CopperGenie** [NyaaCat/RPGitems-reloaded#93]
If an item has durability, the togglebar is always shown, whether or not it is turned on makes no difference.

**Comment by RecursiveG** [comment]
Does that item have a vanilla durability bar?
If it doesn't, the lore bar cannot be hidden otherwise players will not know the durability remains.

**Comment by CopperGenie** [comment]
Okay, thanks a lot!

**Comment by CopperGenie** [comment]
I have another question, though. Is the armor percentage the percent of the whole armor bar? Like, if a piece of armor has 20% armor, does it have armor equivalent to 20% of the armor bar (i.e. 4 points)?

**Comment by RecursiveG** [comment]
No, It reduces the total damage by 20%.
