### ISSUE TITLE
WorldGuard support set true, where is the compability?

### ISSUE THREAD

**Issue by Laos1996** [NyaaCat/RPGitems-reloaded#95]
So, I've set in config 
"support:
  worldguard: true"
Yet I need help how could I make it so in certain regions they cannot use spells, like that ice card from tutorial, problem is, on throw, it will decimate item frames which means theres potential to grief protected areas.

**Comment by Formula350** [comment]
As a helpful tip: If you can tell them what version of Spigot or CraftBukkit you're using, what version of RPGItems, and what version of WorldGuard that you're all running, they'll be able to more easily help narrow down if it is something with RPG or something with WorldGuard (and thus would need to be reported to them).

**Comment by Laos1996** [comment]
WorldGuard 6.1
PaperSpigot 1.8.8
Latest RPGItems keep them up to date

**Comment by Formula350** [comment]
I can say that on Spigot 1.8.8 and WorldGuard 6.1 (which is what I'm running), everything works good when RPGItems Config.yml is set to: 
```yaml
support:
  worldguard: true
```

- If the Region has the Flag set to `PVP: Deny` it prevents RPGItems from activating the Powers *and* players cannot hit each other..
- If the Region has the Flag set to `PVP: Allow` **OR** Does not have PVP set (such as with `__global__`), RPGItems Powers work and players *can* hit each other.

I again am suspecting PaperSpigot may be the problem. .
