### ISSUE TITLE
problem with the power rumble and lifesteal

### ISSUE THREAD

**Issue by Richard0182** [NyaaCat/RPGitems-reloaded#98]
- Power does not work alone rumble particles remain still and doing nothing
- Lifesteal the probability does not work and neither did the power look in the item

I hope and the faster you solve no more to say thanks for the plugin :D

**Comment by Formula350** [comment]
Are you using WorldGuard plugin? Do you have WorldGuard compatibility turned on in config.yml? If you are, run the command `/rg flags <region name> pvp allow` and see if that helps. If you do not know the name of the region use`/rg info` and it will tell you all the names of the regions you're standing in. (Hopefully it is only 1 region.)

If there are multiple regions, you'll have to find out the parent region **or** the region with the highest priority, and set `pvp allow` on that one.

You should also tell the developers of plugins when you report a bug, what the version numbers are of their plugin, Spigot or CraftBukkit, and any other plugins that might be helpful.

**Comment by RecursiveG** [comment]
What version of server and plugin and what language are you using?

Can you provide a way to reproduce the rumble problem?
